### ISSUE TITLE
bug反馈，当分享目标是单个文件的时候，--path-prefix参数失去作用

### ISSUE THREAD

**Issue by vip123456789** [sigoden/dufs#101]
bug反馈，当分享目标是单个文件的时候，--path-prefix参数失去作用。
举例说明：dufs.exe -p 80 --path-prefix 001 f:\dir123\123.mp4
此时http://127.0.0.1:80/001/ 和 http://127.0.0.1:80/ 均可访问到123.mp4文件

若分享目标是文件夹的时候，一切正常。

另，建议提供--random-route参数，随机生成字符串

**Comment by sigoden** [comment]
不明白为什么单个文件还需要路由？

**Comment by sigoden** [comment]
不会提供 --random-route，没有必要，如果一定要随机，你可以这样 `dufs --path-prefix r$RANDOM`

**Comment by vip123456789** [comment]
> 不明白为什么单个文件还需要路由？

比如说，不想让直接访问根路径，只访问特定的路由

**Comment by sigoden** [comment]
也行。稍后会让  `--path-prefix` 也作用于单个文件
