### ISSUE TITLE
Full webdav support

### ISSUE THREAD

**Issue by nicolaspernoud** [sigoden/dufs#104]
## Specific Demand

It would seem that running the litmus test suite (https://github.com/tolsen/litmus / http://webdav.org/neon/litmus/) gives only a very partial webdav support (a lot of errors with copy and move, notably non support of directories, etc.).

It seems that the partial support causes problems when for example copying from command line in linux on a mounted (with gnome file manager) dav : the copy is stuck...

## Implement Suggestion

It would be nice that the webdav server complies with (at least), the "http basic copymove locks props" tests of the litmus test suite.

Best regards.

**Comment by sigoden** [comment]
Full webdav support is not a design goal of dufs. The current implementation is compatible with most of the use cases of most users while keeping it simple.

Can you combine the logs to troubleshoot where the problem is? I'll see if I can fix it?

**Comment by nicolaspernoud** [comment]
Thanks for answering so quickly. There is no logs since the copy is just stuck, but I am pretty sure the problem is related to the fact that the COPY and MOVE methods do not accept directories.
If you were to implement it, maybe you can get some inspiration from https://github.com/messense/dav-server-rs/blob/main/src/handle_copymove.rs (?).

**Comment by nicolaspernoud** [comment]
It occurs immediately when trying to copy a directory : from the GUI it works fine, but from the command line it just does not do anything... This is the same with large or small files...

**Comment by sigoden** [comment]
Could you post the command line? Let me try.

**Comment by nicolaspernoud** [comment]
`cp -r test01/ test01-2/` from a webdav mount made with gnome file explorer

**Comment by sigoden** [comment]
I just try copying to/from `/run/user/1000/gvfs/dav:host=localhost,port=5000,ssl=false/` mount with nautilus. everything works fine.

dufs logs all http requests. if  no logs, means no requests. your should check your tools or operations.
