### ISSUE TITLE
symbolic links to external drives are not listed

### ISSUE THREAD

**Issue by notjedi** [sigoden/dufs#106]
**Problem**

as the title suggests, symbolic links linked to external disks are not listed.

**Environment:**
 - Dufs version: `0.26.0`
 - Browser/Webdav Info: `brave` on android and `librewolf` on linux
 - OS Info: `Arch Linux`

**Comment by notjedi** [comment]
similar projects that are not suffering from this issue:
1. https://github.com/thecoshman/http
2. https://github.com/svenstaro/miniserve

**Comment by notjedi** [comment]
i can see that both the projects do something similar with `fs::read_link`, which `dufs` does not. here is a link to those lines:

https://github.com/thecoshman/http/blob/7c1fa0e7bb5277f201c898fc3f918265c848a0e7/src/ops/webdav.rs#L148-L161

https://github.com/svenstaro/miniserve/blob/master/src/listing.rs#L248-L251

**Comment by sigoden** [comment]
Do your run with option `-A` or `--allow-symlink`?

**Comment by notjedi** [comment]
it works after passing the `-A` option. but i think it makes more sense to allow symlinks by default. also there is lack of consistency here, because symlinks within the same drive are listed without the `-A` option.

**Comment by sigoden** [comment]
For security, dufs don't allow symlinks  to dirctories outside the entrypoint directory unless runing with option `-A` or `--allow-symlink`.
For convenient, dufs do allow symlinks to directories inside the entrypoint directory.

These will satisfy most users.

**Comment by notjedi** [comment]
cool, understood. but, do you mind telling me about the security concerns when it comes to external symlinks?

**Comment by sigoden** [comment]
If you only want to serve a certain directory, but that directory has an symlink which links to /, you are actually exposing the entire filesystem.
