### ISSUE TITLE
auth timeout question

### ISSUE THREAD

**Issue by leolulu** [sigoden/dufs#109]
Hi sigoden,

I'm wondering if there is a time limit for the auth.

Cuz sometimes after several minutes, the auth dialog pops up again. The duration is not quite sure, so that's why I inquire.

And due to the circumstances above, When I upload a large number of files, the latter parts may fail. After the failure shows up, I refresh the page, and the auth dialog pops up, so I guess losing the auth session caused that, maybe.

Please share your opinion on this, Thanks.

**Comment by sigoden** [comment]
Yes, digest authentication has a 5s default timeout. I will adjust it to 1 day.
