### ISSUE TITLE
界面美化

### ISSUE THREAD

**Issue by fcwys** [sigoden/dufs#111]
希望能美化下界面，自适应这种，不知道是否有这方面计划呢

例如类似这种：
![image](https://user-images.githubusercontent.com/28641034/180629700-84b6c2e3-778d-4996-8d1f-b22f3119c6c8.png)

**Comment by sigoden** [comment]
已经是自适应的了。


![Snipaste_2022-07-25_09-46-45](https://user-images.githubusercontent.com/4012553/180677738-a1ad26dc-2c34-486d-9af8-71842f194a09.png)
![Snipaste_2022-07-25_09-44-48](https://user-images.githubusercontent.com/4012553/180677753-667878a7-797f-486e-a205-7e0a78f2ba10.png)

dufs中尽可能多的展示文件名很重要（尤其是搜索结果），所以没有采用常规的限宽居中布局，而是左对齐文件栏自动伸缩。

基于这种布局，表格样式意义不大。
