### ISSUE TITLE
是否考虑增加日志路径和展示用户ua

### ISSUE THREAD

**Issue by qiaoruntao** [sigoden/dufs#112]
增加日志主要是为了在开放访问目录的情况下留存访问记录, 便于追溯是谁访问了文件.
例如增加`--log="some-path"`选项, 将访问日志写入指定的文件.
增加User Agent是为了方便区分不同的访问设备, 现在命令行日志只提供了ip和访问路径, 这个信息量有点少了.

**Comment by sigoden** [comment]
日志文件可以这样实现：dufs > /var/log/dufs.log
展示UA不是很普遍的需求，你可以加一层代理 (如nginx)

**Comment by qiaoruntao** [comment]
主要之前用习惯了[http-server](https://github.com/http-party/http-server), 默认展示ua很方便. 如果需要套一层nginx就有点缺少灵活性了

**Comment by sigoden** [comment]
#116 支持自定义日志格式，这个issue就关闭了。

**Comment by qiaoruntao** [comment]
感谢
