### ISSUE TITLE
readonly can not work

### ISSUE THREAD

**Issue by Xiechengqi** [sigoden/dufs#125]
**Problem**
readonly can not work

```
dufs -a <path>@<readwrite>[@<readonly>|@*]
```

Could you add some example about how to set <path> readwrite or readonly, Thanks !

**Comment by sigoden** [comment]
```
dufs -A -a /@admin:pass1@admin2:pass2
```
admin is a readwrite account with all permissions.
admin2 is a readonly account with view/download permissions.
