### ISSUE TITLE
希望可以在IE浏览器中支持最基本的浏览和下载功能

### ISSUE THREAD

**Issue by hhs66317** [sigoden/dufs#132]
## Specific Demand

到一台新电脑上，可能没有第三方的浏览器，只能使用自带的IE浏览器，此时需要能通过IE浏览器在 dufs 中下载一些文件，来构建自己的使用环境，因此有必要在IE浏览器中提供最基本的浏览和下载功能，当然如果能都实现，那就超出预期的完美了。

## Implement Suggestion

我当前使用的类似软件是 chfs ，这个软件是支持在常规的各种浏览器中正常使用的，包含对IE的支持，遗憾的是它不能移动文件和目录。

**Comment by sigoden** [comment]
经典语录：IE 就是用来下载 chrome 的。你的问题最好的解决方案就是下载 chrome 然后使用 chrome。

**Comment by hhs66317** [comment]
经典语录：不支持的话，也可以换个支持的用，有同样需求的可以试试 chfs

**Comment by gongkangjia** [comment]
同希望！因为这个放弃使用dufs了
