### ISSUE TITLE
webdav 希望能支持 lock 和 unlock

### ISSUE THREAD

**Issue by hhs66317** [sigoden/dufs#133]
## Specific Demand

我当前使用的 keepassXC 是支持 webdav 加载远端密码库的，需要用到 lock 和 unlock 来保证数据库的正确性

## Implement Suggestion

当前支持的 webdav 方法有 GET,HEAD,PUT,OPTIONS,DELETE,PROPFIND,COPY,MOVE

增加 LOCK 和 UNLOCK 就可以了，至于更多的方法使用场景就更广泛了

**Comment by sigoden** [comment]
dufs 服务也是无状态，突出特点的简洁精炼，目前的webdav特性已经能满足绝大多数场景了。

如果需要用到lock/unlock，建议还是使用专门的webdav服务器。

**Comment by hhs66317** [comment]
你说的对，还是继续用现在的 nginx 好
