### ISSUE TITLE
在网页中打开可读文件比如 .md 文件时中文乱码

### ISSUE THREAD

**Issue by icxksdkc** [sigoden/dufs#139]
## Specific Demand
希望对于在浏览器中可读的文件, 能够正常阅读中文.

## Implement Suggestion
在返回的 content-type 中加入 utf-8.

**Comment by sigoden** [comment]
dufs 返回的 content-type 不带 charset，表示使用浏览器默认编码（通常utf8）。只有文件编码格式与浏览器默认编码不一致才会显示乱码。

不是所有文件都是utf8的，没法直接在 content-type 中加入charset=utf-8。而对每个文件进行一次编码辨别又比较耗费资源，过于鸡肋。所以通常不带 charset
