### ISSUE TITLE
how to disable Download folder as zip file ?

### ISSUE THREAD

**Issue by humbinal** [sigoden/dufs#148]
Hi,
  I want to disable the function `Download folder as zip file`，sometimes there are a lot of very large files in the directory， download all of them It's very dangerous and expensive.
  I didn't see this function when I read the document. do you support this function? 
 Thank you.

**Comment by sigoden** [comment]
Will add `--allow-zip-folder` option to explicitly allow download folder as zip file

**Comment by sigoden** [comment]
maybe next week
