### ISSUE TITLE
The dufs docker image does not terminate properly

### ISSUE THREAD

**Issue by sprat** [sigoden/dufs#150]
**Problem**

The dufs docker image does not terminate properly: the dufs server seems to shutdown only with the Ctrl+C (SIGINT) signal, but  docker send a SIGTERM signal to stop the process by default. Since the process does not shut down, docker send a SIGKILL signal after 10s which stops the process without any cleanup.

Either dufs should react to the SIGTERM signal, or the dufs docker image should specify a SIGINT signal as stop signal (via the STOPSIGNAL directive in the Dockerfile).

**Log**

When I stop the container, it takes 10s to shutdown instead of shutting down immediately.

**Environment:**
 - Dufs version: 0.31.0
 - Browser/Webdav Info: NA 
 - OS Info: docker image on amd64 host

**Comment by sprat** [comment]
Note: I can file a pull request adding the STOPSIGNAL directive if you agree with the approach

**Comment by sigoden** [comment]
welcome to submit a pr to add STOPSIGNAL directive to Dockerfile.

**Comment by sprat** [comment]
done ;)
