### ISSUE TITLE
Upload equivalent for download folder as zip

### ISSUE THREAD

**Issue by macabrus** [sigoden/dufs#153]
## Specific Demand

It would be cool if users could have equivalent of 'Download as zip' (?zip query param) for uploading, maybe for bulk uploading whole directory

## Implement Suggestion

I suggest same API as current downloading option:
GET /path/to/dir?zip
POST /destination/root?zip (it could use mkdir -p to create missing dirs)

Upload could probably be stream decompressed into dir directly and iterated over zip-entries but you could also create temp dir and move to final destination later.

**Comment by sigoden** [comment]
It's easy to upload a folder using the UI or webdav client.

Even in a terminal, it's also easy for you to upload a folder with ` find . -type f | xargs -I{} curl -T{} http://127.0.0.1:5000/{}`.

It has been opened for 2 months, and there are not many people who like it.

After weighing it, I'm still not ready to support this feature. Hope you can understand.

**Comment by lukasjuhrich** [comment]
FWIW: In case this is not obvious, to upload a whole directory structure, you can issue a `MKCOL` with `find . -type d` before uploading the files:
```shell
find . -type d | xargs -I{} curl -X MKCOL http://127.0.0.1:5000/{}
find . -type f | xargs -I{} curl -T{} http://127.0.0.1:5000/{}
```

Although zip upload would be nice eventually, this should suffice for the time being.
