### ISSUE TITLE
 dufs-v0.31.0-i686-unknown-linux-musl.tar.gz miss option --allow-archive

### ISSUE THREAD

**Issue by laminux29** [sigoden/dufs#155]
**Problem**

#==============================
root@Test-Debian-11-4-0-AppTest:~# dufs /www_dufs/ --bind 0.0.0.0 --port 443 --allow-search --enable-cors --allow-archive
error: Found argument '--allow-archive' which wasn't expected, or isn't valid in this context

  Did you mean '--allow-search'?

Usage: dufs --bind <addrs> --port <port> --allow-search --enable-cors <root>

For more information try '--help'

#==============================
root@Test-Debian-11-4-0-AppTest:~# dufs --help
Dufs is a distinctive utility file server - https://github.com/sigoden/dufs

Usage: dufs [OPTIONS] [root]

Arguments:
  [root]  Specific path to serve [default: .]

Options:
  -b, --bind <addrs>         Specify bind address or unix socket
  -p, --port <port>          Specify port to listen on [default: 5000]
      --path-prefix <path>   Specify a path prefix
      --hidden <value>       Hide paths from directory listings, separated by `,`
  -a, --auth <rules>         Add auth for path
      --auth-method <value>  Select auth method [default: digest] [possible values: basic, digest]
  -A, --allow-all            Allow all operations
      --allow-upload         Allow upload files/folders
      --allow-delete         Allow delete files/folders
      --allow-search         Allow search files/folders
      --allow-symlink        Allow symlink to files/folders outside root directory
      --enable-cors          Enable CORS, sets `Access-Control-Allow-Origin: *`
      --render-index         Serve index.html when requesting a directory, returns 404 if not found index.html
      --render-try-index     Serve index.html when requesting a directory, returns directory listing if not found index.html
      --render-spa           Serve SPA(Single Page Application)
      --assets <path>        Use custom assets to override builtin assets
      --tls-cert <path>      Path to an SSL/TLS certificate to serve with HTTPS
      --tls-key <path>       Path to the SSL/TLS certificate's private key
      --log-format <format>  Customize http log format
      --completions <shell>  Print shell completion script for <shell> [possible values: bash, elvish, fish, powershell, zsh]
  -h, --help                 Print help information
  -V, --version              Print version information

#==============================
root@Test-Debian-11-4-0-AppTest:~# dufs --version
dufs 0.31.0

#==============================

**Environment:**
 - Dufs version:  dufs-v0.31.0-i686-unknown-linux-musl.tar.gz
 - OS Info: Debian 11.4.0 x86_64

**Comment by sigoden** [comment]
[`--allow-archive](#152) is a newly merged feature, not released yet.
