### ISSUE TITLE
recommend output logs like nginx.

### ISSUE THREAD

**Issue by laminux29** [sigoden/dufs#156]
Nginx has two types of logs:

/var/log/nginx/access.log

/var/log/nginx/error.log

It is recommended to output log files to /var/log, a directory dedicated to storing logs.

Maybe:

/var/log/dufs/access.log
and
/var/log/dufs/error.log

or

/var/log/dufs_access.log
/var/log/dufs_error.log

**Comment by sigoden** [comment]
dufs don't output any error, do print access log to stdout.

run `dufs > /var/log/dufs_access.log` to store access log.
