### ISSUE TITLE
Upload Button does not pop up a login dialog box every time. 

### ISSUE THREAD

**Issue by laminux29** [sigoden/dufs#157]
**Problem**

Upload Button does not pop up a login dialog box every time. 

But Create a new folder Button can make the browser pop up the login dialog box every time.

command:
dufs /www_dufs/ \
    -A \
    -a /@admin:admin123@* \
    --bind 0.0.0.0 \
    --port 80 \
    --enable-cors

**Environment:**
 - Dufs version: dufs-v0.31.0-i686-unknown-linux-musl.tar.gz
 - Browser/Webdav Info: Chrome 108.0.5359.72 (64 bit)
 - OS Info: Debian 11.4.0 x86_64

**Comment by Jlll1** [comment]
And I'd say another issue with the login dialog during upload is that it's displayed after the file is sent to the server, not before.

**Comment by TravinDreek** [comment]
Same issue that's been troubling me for long. A temporary workaround is to rename a random file first to trigger an auth pop-up, which will later free you from the auth bug of uploading.
