### ISSUE TITLE
Some suggestions for log in option.

### ISSUE THREAD

**Issue by laminux29** [sigoden/dufs#158]
Suggestion:

1. Add a user login button if no one log in.

2.Add a logout button if someone logged in.

3.Add a Label that displays the userName. Display Guest if no log in.

**Comment by sigoden** [comment]
pr #182 solves 1 and 3.

As for the second point, dufs supports two forms of login basic/digest auth. Both login methods use the browser's built-in login pop-up window. After closing the browser, you will be logged out, and you cannot manually log out in webpage
