### ISSUE TITLE
suggestion for Debian 11 Systemd Service

### ISSUE THREAD

**Issue by laminux29** [sigoden/dufs#159]
# Tested for debian 11
#
# Please loggin as root
#
# 1.Create folder for www datas
mkdir -p /www_dufs
#
# 2.Create folder for certs
mkdir -p /www_dufs_certsOnly
#
# 3.Write a starup script
echo "dufs /www_dufs/ --bind 0.0.0.0 --port 443 --allow-search --enable-cors --tls-key /www_dufs_certsOnly/xx.key --tls-cert /www_dufs_certsOnly/xx.cert >> /var/log/dufs.log" > /startDufs.sh
chmod ugo+rwx /startDufs.sh
#
# 4.Write systemd service
tee /etc/systemd/system/dufs.service <<-"EOF"
[Unit]
Description=dufs
After=network.target auditd.service

[Service]
ExecStart=sh /startDufs.sh

[Install]
WantedBy=multi-user.target
EOF
#
chmod ugo+wrx /etc/systemd/system/dufs.service
systemctl daemon-reload
systemctl enable dufs.service
#
# 5.reboot, then dufs service will auto startup on boot.
shutdown -r now
#
# 6.Check log:
tail -f /var/log/dufs.log
#
# 7.Alive check:
netstat -nlap | grep "LISTEN" | grep ":443"
#
# 8.Control Dufs Service:
systemctl status dufs
systemctl start dufs
systemctl restart dufs

**Comment by sigoden** [comment]
Thanks for sharing.

**Comment by hastalamuerte** [comment]
maybe it can be installed as service ? to run with args like systemctl start dufs -A  - by default install with cargo?
? it will be very helpfull
