### ISSUE TITLE
Ability to hide all directories, but not files

### ISSUE THREAD

**Issue by Jlll1** [sigoden/dufs#162]
## Specific Demand
Currently, we are able to hide all files by simply passing `*` to `--hidden`, but there is no way to distinguish between files and directories and more complex globbing patterns don't seem to be working (such as `*/`).
I'd like to have a setup where all the directories are hidden, but once an user has the link to a directory, then he can see all files inside it.
Now, this is achievable by just listing out all directories as an input to `--hidden`, but such configuration would have to get updated each time a new directory is added.

## Implement Suggestion
I think the best way to have this implemented would be to have support for globbing patterns such as `*/`.
Another approach would be to add 2 new commands `--hidden-files` and `--hidden-dirs` where `--hidden` would be a combination of these two. I'm not sure if I like that personally, but that's definitely an option.

**Comment by zanderzhng** [comment]
I'd like the ability to hide files as well, not only hiding directories.
