### ISSUE TITLE
Support webdav, what does that mean?

### ISSUE THREAD

**Issue by FunDeckHermit** [sigoden/dufs#164]
**Problem**
I have a WebDAV server using [Rclone](https://rclone.org/commands/rclone_serve/) which works great. Is Dufs able to forward/proxy that internal WebDAV proxy? 

Or is Dufs just a server for external applications?

**Comment by jacobzeng** [comment]
same question, didn't find how to enable webdav at the docs

**Comment by sigoden** [comment]
Dufs is also a WebDAV server.  It implements the WebDAV protocol, and you connect through a WebDAV client.
