### ISSUE TITLE
[Feature request] API to search and list directories

### ISSUE THREAD

**Issue by 1024bees** [sigoden/dufs#166]
## Specific Demand

An API to search for a file and show contents of a directory.

### list directory API 
curl http://127.0.0.1:5000/path-to-directory?list_contents=true to return a list of this files contents, analogous to running the linux command  `ls /path-to-directory` on the server locally 

### search API 

curl http://127.0.0.1:5000/path-to-directory?search_for=${NAME_STR} would be analogous to running the linux command `find  -L /path-to-directory -name "${NAME_STR}"` on the server locally;

## Implement Suggestion

Haven't thought about this seriously yet; I figure its best to agree on an API

**Comment by sigoden** [comment]
What scenarios need this kind of API ?

**Comment by 1024bees** [comment]
Abstractly, a list directory API would allow end users to build file system abstractions to a given dufs server.

For my use case, I'm building a GUI that when provided a URL  to a `dufs` server, a file tree would be displayed. imagine something like https://doc.qt.io/qt-6/qtwidgets-itemviews-dirview-example.html. the displayed files would be available on the `dufs` server

**Comment by sigoden** [comment]
Maybe add an `output` query string to control the output format

- html: output web page, default
- json: output file list, including file name, size, type and other information
- simple: output only a list of filenames

**Comment by 1024bees** [comment]
Sounds good to me, I'll look to prototype this weekend
