### ISSUE TITLE
Method `options` should not check auth

### ISSUE THREAD

**Issue by horizon0514** [sigoden/dufs#167]
**Problem**
The preflight request will exclude  user credentials
see [stackoverflow](https://stackoverflow.com/questions/40722700/add-authentication-to-options-request)

so when we use `cors` and `auth`, the `options` request will throw 401 error

it should not check the auth of `options` method 

**Environment:**
 - Dufs version: latest
 - Browser/Webdav Info:  Edge
 - OS Info: Mac OS

**Comment by horizon0514** [comment]
maybe I can pull a request

**Comment by sigoden** [comment]
You are welcome to submit a pr
