### ISSUE TITLE
[Feature request] Calculate And Show A File's Checksum

### ISSUE THREAD

**Issue by enchant97** [sigoden/dufs#169]
## Specific Demand
I would like to be able to select a file and calculate a checksum.

## Implement Suggestion
Maybe a button that calculates and opens a window with several different hash methods e.g. md5, sha, sha256

**Comment by sigoden** [comment]
It is unrealistic. Some files may be larger than 10M or even 1G.
It cannot be calculated on the frontend，calculated on the backend need a lot of resources.
It is best to upload the checksum file along with the original file.
