### ISSUE TITLE
Add ability to overwrite files

### ISSUE THREAD

**Issue by babam86** [sigoden/dufs#171]
## Specific Demand

Add ability to overwrite files (upload files).

Thanks.

**Comment by sigoden** [comment]
Overwriting files requires upload and delete permissions. Run `dufs --allow-upload --allow-delete`

**Comment by babam86** [comment]
I used the `--allow-all` option and overwriting files didn't work.

**Comment by sigoden** [comment]
dufs's webdav should support overwriting files.
Colud you describe the operation in detail and provide dufs logs?

**Comment by babam86** [comment]
`dufs` is great, works perfectly. SOLVED
