### ISSUE TITLE
How to download via api if auth is set

### ISSUE THREAD

**Issue by Jiesen-Chen** [sigoden/dufs#181]

**Comment by sigoden** [comment]
For basic auth:
```
curl --user admin:admin http://192.168.8.10:5000/file
wget --user admin --password admin http://192.168.8.10:5000/file
```

In other http client, add header `Authorization: Basic YWRtaW46YWRtaW4=`

For digest auth
```
curl --user admin:admin --digest http://192.168.8.10:5000/file
wget --user admin --password admin http://192.168.8.10:5000/file
```
In other http client, add header `Authorization: Digest username="admin", realm="DUFS", nonce="63f42d2ef777ad88783383c83cd5903932", uri="/", response="23e0b106204a6a0b9c5241e667bda41b", qop=auth, nc=00000002, cnonce="1cee67e83a70d0d6"`
