### ISSUE TITLE
Can't open Webdav with Kodi

### ISSUE THREAD

**Issue by 289699522** [sigoden/dufs#192]
**Problem**
When use Kodi to mount the dufs's Webdav server,it didn' work.
Kodi无法打开dufs的Webdav服务器，但是kodi可以打开其他Webdav服务器。

**Log**
Dufs's log shows the status code is 401.

**Environment:**
 - Dufs version: v0.32.0
 - Browser/Webdav Info: Kodi无法打开
 - OS Info: dufs-v0.32.0-aarch64-unknown-linux-musl.tar.gz

**Comment by sigoden** [comment]
I specifically downloaded kodi, tested it and did not find any issues.
```
dufs -a /@admin:admin
```

![image](https://user-images.githubusercontent.com/4012553/224494084-e9287e4e-faaa-434f-bc17-50d1f1b441f4.png)

If you still have question, please provide more details
- Command
- Logs
- You kodi config

**Comment by 289699522** [comment]
I tested again, found the problem is not caused by kodi. 
I set two users, user1 and user2. I plan to use user1 to access the whole disk, user2 only access the `qbittorrent` dictionary. 
My hard disk is mounted at /media/st_disk, the `qbittorrent` dictionary is located at /media/st_disk/qbittorrent.
`./dufs -a /@user1:pass1 -a /qbittorrent/@user2:pass2 /media/st_disk`
Only user1 can login. user2 can't login both in the browser and WebDAV clients.

**Comment by sigoden** [comment]
How do you config webdav？

A screenshot please.

Or paste you configuration.

**Comment by 289699522** [comment]
Thank you for your reply. But I found a new problem about `--auth-method basic`. 

`./dufs -a /@u1:p1 --auth-method basic`
 The browser repeatedly pops up the login boxand and WebDAV clients also cannot log in.  

`./dufs -a /@u1:p1 --auth-method digest`
 The browser and WebDAV clients support digest can login.

**Comment by sigoden** [comment]
This is not a problem with dufs.

DUFS supports two login methods. Browsers also support both. As for which one webdav mainly supports, it's hard to say, but digest supports more.

**Comment by sigoden** [comment]
If there are no other questions, please close the issue.

**Comment by 289699522** [comment]
Sorry, I didn't explain clearly. I main that when I use `--auth-method basic`, browsers also can't login.
`# $ ./dufs -a /@u1:p1 --auth-method basic`
```
# $ curl http://127.0.0.1:5000/ -I --user u1:p1
HTTP/1.1 401 Unauthorized
allow: GET,HEAD,PUT,OPTIONS,DELETE,PROPFIND,COPY,MOVE
dav: 1,2
connection: close
www-authenticate: Basic realm="DUFS"
```

**Comment by sigoden** [comment]
I have identified the issue, thank you.

I usually tested it with `dufs -a /@user:pass-A --auth-method basic` and haven't noticed any problems.

In previous version, I updated a base64 library, and some configuration adjustments were not noticed, resulting in this issue.

 thank you again.

**Comment by sigoden** [comment]
#194 solved this.
