### ISSUE TITLE
能不能新增文件重命名功能

### ISSUE THREAD

**Issue by yanchenyuvip** [sigoden/dufs#196]
## Specific Demand

能不能新增文件重命名功能

**Comment by sigoden** [comment]
![image](https://user-images.githubusercontent.com/4012553/225799832-b1fc248b-b2c9-405b-a23b-e1cff48162fd.png)

move action can do rename

**Comment by sigoden** [comment]
It is for moving to a new path, and can be used for renaming.

**Comment by sigoden** [comment]
i18n is too complicatd for a simple file server.

So I used icons for the entire ui, avoid text.

**Comment by sigoden** [comment]
supporting multiple langeuages is too complicatd for a simple file server.

I close this issue since your problem was solved
