### ISSUE TITLE
dufs vs miniserve vs others

### ISSUE THREAD

**Issue by stokito** [sigoden/dufs#198]
It was already mentioned in issues these two similar projects:
* https://github.com/thecoshman/http
* https://github.com/svenstaro/miniserve
They both are doing almost the same and also written in Rust.
I wondered what's a difference between all these projects?
Maybe you all can contribute together and make a single perfect thing.

See also https://github.com/yurt-page/docs/blob/main/webservers.md

**Comment by sigoden** [comment]
Good things usually have many competitors.

The user needs to choose the one he thinks is most suitable according to his needs.
