### ISSUE TITLE
增强权限控制，目前的权限控制不够细致

### ISSUE THREAD

**Issue by hhs66317** [sigoden/dufs#199]
目前只能设置不同的账户对不同目录的权限控制，而且权限设定还是全局的

对于权限的设置颗粒度再细化一些：
admin用户对所有目录 / 具有全部权限
A用户对/A目录具有全部权限，/B目录无权限，其他目录只读
B用户对/B目录只有上传，删除权限，其他目录只读
未登录状态，可以对指定目录只读，对指定目录无访问权限

**Comment by sigoden** [comment]
感谢您的提案。 但我认为dufs没有必要修改当前的权限系统。

DUFS 首先是个 File Server，后面添加了 Webdav，使得其可以当成网盘。
但它的不是一个典型的网盘，就如在权限系统上 DUFS 是基于路径的，而不是基于用户。

用户应该基于实际需求设计目录，在把目录对应读写账户分配到特定人手上。

如果只给用户上传权限但不给删除权限，那上传失败怎么办？
再次上传是不是就是在删除已经存在的文件，不让再次上传就有个破损了文件存在了。
所以权限只分读写，不分上传，删除，移动，修改。
