### ISSUE TITLE
Support QRCode code generate

### ISSUE THREAD

**Issue by kmephistoh** [sigoden/dufs#211]
## Specific Demand

If dufe support QRCode code generate, that will be useful for mobile phone.

## Implement Suggestion
Just like [gohttpserver](https://github.com/codeskyblue/gohttpserver)

**Comment by sigoden** [comment]
modern browsers already supports qr, I don't think qr is necessary.

chrome:
![image](https://github.com/sigoden/dufs/assets/4012553/9391c222-31fe-4bdf-ac38-628efb594f7f)

edge:
![image](https://github.com/sigoden/dufs/assets/4012553/1ad514f4-4a16-44d8-9555-584315b42f45)

**Comment by kmephistoh** [comment]
You are right, thanks for your reminder.
