### ISSUE TITLE
无法上传4G以上的大文件

### ISSUE THREAD

**Issue by wuzhaohui100** [sigoden/dufs#212]
上传大于4G的大文件会中断，服务端报错：500 error reading a body from connection: end of file before message length reached

**Environment:**
 - Dufs version:0.33.0
 - Browser/Webdav Info: 
 - OS Info: linux

**Comment by sigoden** [comment]
dufs does not limit upload file size.
This error is a network problem,  the network was interrupted during the uploading.
The larger the file, the greater the probability of encountering network failures.
