### ISSUE TITLE
How can I see the real ip with reverse proxy?

### ISSUE THREAD

**Issue by xrfmkrh** [sigoden/dufs#217]
## Specific Demand
I set this with Traefik(docker). but in my logs, I can't see real ip. I only can see Traefik's ip.
ex)INFO - 172.16.0.2 "GET /complete/" 200
Not happen to my other container(Authelia, Filebrowser, and so on) with Traefik. Those show real ip at logs.

## Implement Suggestion
change logs to show real ip in reverse proxy

**Comment by sigoden** [comment]
see readme #log-format. replace `$remote_addr` with `$http_x_real_ip` or `$http_x_forwarded_for`
