### ISSUE TITLE
broken folder in folder when zip

### ISSUE THREAD

**Issue by Asmaelh** [sigoden/dufs#227]
When you download a folder that has more folders as a zip archive, the folder structure in the archive is not saved, but only the files with folder names are created.
![Снимок экрана (10)](https://github.com/sigoden/dufs/assets/68203392/853a58ca-572c-4113-b68f-5b2580c7a99b)

 - Dufs version: 0.34.1
 - Browser/Webdav Info: Mozila Firefox
 - OS Info: Windows 10

**Comment by sigoden** [comment]
I didn't find the problem you said, is it a problem with your compression software?

**Comment by Asmaelh** [comment]
Hmmm... Yes, you're right, 7zip doesn't open archives like that correctly. It opens everything perfectly in Total Commander, thanks.
