### ISSUE TITLE
Is authentication done in constant time for Basic Authentication ?

### ISSUE THREAD

**Issue by perrinjerome** [sigoden/dufs#228]
**Problem**

If I understand correctly, when running with `--auth-method basic`, this 

https://github.com/sigoden/dufs/blob/4f3a8d275b7f2904ec2e16a0a8e54e4a9bec1986/src/auth.rs#L309-L315

is not comparing the password using constant time, which is not recommended according to 
https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#compare-password-hashes-using-safe-functions

Maybe something like https://docs.rs/constant_time_eq/latest/constant_time_eq/ could be used instead, but I don't know much about rust ecosystem so I am can not really recommend any implementation.

**Log**

If applicable, add logs to help explain your problem.

**Environment:**
 - Dufs version: 0.42.1
 - Browser/Webdav Info: 
 - OS Info:

**Comment by sigoden** [comment]
This is over optimized
