### ISSUE TITLE
Support for No-Console Start Mode on Windows

### ISSUE THREAD

**Issue by chenghongyao** [sigoden/dufs#232]
## Specific Demand

Is it possible to support a mode that does not display the terminal window on Windows? I would like to start it automatically at system startup, but I don't want to display the terminal window.

## Implement Suggestion

This feature is implemented in another software  [Syncthing ](https://syncthing.net/) I use by adding parameters `--no-console --no-browser`.

**Comment by sigoden** [comment]
No, use sc, nssm, pm2 or docker.
