### ISSUE TITLE
Support for special characters in passwords

### ISSUE THREAD

**Issue by narigondelsiglo** [sigoden/dufs#236]
## Specific Demand

I need to be able to use credentials that may contain "special characters" like the ones used to parse the rules, ie. `|@:`

## Implement Suggestion

Maybe it could be done by allowing one to use base64 encoded passwords, and have a new argument like `--auth-encoded` to let the parser know the password is encoded.

**Comment by sigoden** [comment]
In addition to `|@`, there are more than 90 characters to choose from, enough for a password.
