### ISSUE TITLE
Fail to install dufs on my RISC-V board

### ISSUE THREAD

**Issue by ifsheldon** [sigoden/dufs#238]
**Problem**
I failed to install duds on my RISC-V board. And I think this is due to `ring`. 

While you cannot fix this in a simple way, maybe you can add a feature gate to not compile all the code related to TLS which may indirectly depend on `ring`? Because I want to use `dufs` in my private network, I don't need secure connections.

**Log**
After `cargo install dufs`, I got the following
```
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installpE8QKz/release/build/ring-77603510dd18e4b3/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/ring-0.16.20/build.rs:358:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `dufs v0.34.2`, intermediate artifacts can be found at `/tmp/cargo-installpE8QKz`
```

**Environment:**
 - Dufs version:
 - Browser/Webdav Info: 
 - OS Info: Debian RISC-V port

**Comment by sigoden** [comment]
you can try `cargo install --no-default-features dufs`.

Note: The tls feature of dufs depends on rustls, and rustls depends on ring. But ring does not support risc-v.

**Comment by ifsheldon** [comment]
Thanks a lot! I got it working! I suggest to add a tip in README to tell users that dufs can be compiled without TLS so possibly many many arch can run it without ring getting in the way.
