### ISSUE TITLE
file search optimize

### ISSUE THREAD

**Issue by image72** [sigoden/dufs#240]
## Specific Demand

file search too slow

## Implement Suggestion

use  [tantivy](https://github.com/quickwit-oss/tantivy) speed up file search. rust friendly.
demo integration 
[orange. Cross-platform local file search engine](https://github.com/naaive/orange)

**Comment by sigoden** [comment]
First of all thanks for your suggestion.

After oange starts, it will walk the directory, collect metadata of all files in the directory, then store them into the tantivy full-text index database. At the same time, orange also starts watcher to monitor file system changes and synchronize the database.

The search of dufs is not a high-frequency requirement. Optimizing search following your suggestion will cause slow startup or unavailable search at launch (It takes time to walk file system to build index). If the index is saved to a file, it violates the stateless promise of dufs. If it is saved to memory, it consumes more memory. Watch  file system also consumes resources. And dufs also supports symlink, if someone accidentally links the C drive, I don't know what will happen.

so i'm not going to take your suggestion.
