### ISSUE TITLE
MORE MODERN AND SIMPLE UI

### ISSUE THREAD

**Issue by rakhaevandy27** [sigoden/dufs#249]
hey there,
i want to thank you about this project, and i use it a lot for retrieve an uploaded homework for all my friend at school as my teacher ask me to collect it.

It would be cool if the UI is more modern and simple look😉👌

sincerely,me

**Comment by sigoden** [comment]
The current UI of dufs is good enough.

you can create/use your ui with ` --assets <dir>` if you needs.

**Comment by rakhaevandy27** [comment]
yes sir👍
