### ISSUE TITLE
blocked by MS denfender

### ISSUE THREAD

**Issue by kabylake2** [sigoden/dufs#251]
**Log**
![Capture](https://github.com/sigoden/dufs/assets/34359020/ed7788eb-3e78-406a-ac9a-c3461619264a)
[](url)
**Environment:powershell
 - Dufs version: 0.34.2
 - Browser/Webdav Info: 
 - OS Info: win10

**Comment by graphixillusion** [comment]
yep, this is the current virustotal detections list:

https://www.virustotal.com/gui/file/000fb965c51476f7e173e09cfd90cc6bb27342fa8218926747b9e1e48a30c087?nocache=1

**Comment by sigoden** [comment]
Recommend [dufs v0.36.0](https://github.com/sigoden/dufs/releases/tag/v0.36.0).
