### ISSUE TITLE
simplest launch command to be readonly for everyone

### ISSUE THREAD

**Issue by LeiYangGH** [sigoden/dufs#256]
## Specific Demand

i want simplest launch command to serve file be readonly for everyone
currently i use `dufs -A -a @/`
but it still renders edit and delete buttons, which prompt auth dialog when clicked. this ui is unwanted.

## Implement Suggestion

provide a command to serve readonly files for everyone, and ui having no edit and delete buttons.

**Comment by babyshen** [comment]
`./dufs -p 9090 -a admin:admin@/:rw`
