### ISSUE TITLE
Failed to upload large file

### ISSUE THREAD

**Issue by pinghe** [sigoden/dufs#257]
**Problem**

Failed to upload large file, 7.5g only 3.5g uploaded.

**Log**

```
127.0.0.1 "PUT /data/file.img" 500 error reading a body from connection: end of file before message length reached
```

**Environment:**
 - Dufs version:  0.35.0
 - Browser/Webdav Info:  chrome
 - OS Info:  linux ubuntu 22.04

**Comment by sigoden** [comment]
Unstable network during uploading caused this error

**Comment by pinghe** [comment]
is localhost

**Comment by sigoden** [comment]
dufs doesn't have any restrictions on uploads. If the upload fails, it may end up with an unstable network or insufficient disk
