### ISSUE TITLE
Windows Binary blocked by MS Defender (new trojan flagged?)

### ISSUE THREAD

**Issue by cokelly** [sigoden/dufs#259]
**Problem**

The latest dufs windows binary is flagged as containing Trojan _AgentTesla!ml_ as below:

![image](https://github.com/sigoden/dufs/assets/1672300/6c523d30-4eef-4dbb-afed-d0cba7c354cd)

This seems on the face of it to be different to #251 which flagged a Trojan identified as _Malgent!MSR_.

**Environment:**
 - Dufs version: 0.36.0
 - OS Info: W11

**Comment by sigoden** [comment]
Please updaet windows security to latest malware definition and try again

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

If malware detection still exists, you can [Sumit a file for malware analysis](https://www.microsoft.com/en-us/wdsi/filesubmission)

**Comment by cokelly** [comment]
Ah - apologies. Once this morning's Defender definitions update ran the file was no longer flagged.
