### ISSUE TITLE
Add external authenticator header for reverse proxying

### ISSUE THREAD

**Issue by Pikaro** [sigoden/dufs#260]
## Specific Demand

Allow trusting an `X-Remote-User` or similar header which would denote the logged-in user. This is a common feature in environments using reverse proxies where authentication is often externalized to SSO services or similarly more complex than the current authentication scheme allows.

The `-a` option would have to be adapted to make the password optional without implying "passwordless" and to accept a `%u` or similar placeholder for the remotely logged-in user. This would allow settings like "each user can access their own home directory". 

Adding other settings commonly used in this context, such as

- a "trusted proxies" comma-separated list of CIDR subnets
- a "forwarded IP / Proto header" setting
- an "external hostname" setting
- etc

would be useful in a reverse-proxied environment as well.

**Comment by sigoden** [comment]
Use proxy server authentication alone，or use dufs authentication alone，Mixing these together can be both intricate and prone to errors.

**Comment by ItalyPaleAle** [comment]
I would love support for "pass-through authentication" too, where the proxy authenticates users and dufs uses the value supplied by the proxy (e.g. the "x-forwarded-user" header).

Alternatively, support for authentication via OAuth2 ("Bearer" authorization headers) could work too!
