### ISSUE TITLE
Escaping field separators of `-a` option not possible

### ISSUE THREAD

**Issue by Pikaro** [sigoden/dufs#261]
**Problem**

Specifying login usernames or scopes containing `@` (and likely other special characters used for field separation) is not possible or the syntax is not explained. Please specify the syntax or allow escaping / circumventing, e.g. by allowing percent-encoded values for each field of the `-a` option.

**Log**

n/a

**Environment:**
 - Dufs version: v0.36.0
 - Browser/Webdav Info: n/a
 - OS Info: Docker scratch container

**Comment by sigoden** [comment]
dufs prefers ease of use over versatility, don't use the `@` character as your username or password and you'll be fine
