### ISSUE TITLE
Cannot edit because file is too large or binary.

### ISSUE THREAD

**Issue by flyhigh318** [sigoden/dufs#265]
**Problem**
when I edit app.js on  dufs web site, it happens like this: Cannot edit because file is too large or binary.

**Log**
If applicable, add logs to help explain your problem.

Cannot edit because file is too large or binary.

**Environment:**
 - Dufs version:  dufs 0.34.2
 - Browser/Webdav Info:  chrome 115.0.5790.170 x86_64
 - OS Info:  mac 12.4

**Comment by sigoden** [comment]
File size > 4M is too large for editing.
