### ISSUE TITLE
upload/delete doesn't work on termux (android)

### ISSUE THREAD

**Issue by zirf0** [sigoden/dufs#266]
**Problem**

dufs run

dufs -A -a admin:123@/ --auth-method basic

verify

curl --user admin:123 http://127.0.0.1:5000/token.txt           2023-09-18T12:31:40+03:00 INFO - 127.0.0.1 "GET /token.txt" 200

curl --user admin:123 --basic -T $work/test.sh http://127.0.0.1:5000/test.sh                              2023-09-18T12:32:31+03:00 INFO - 127.0.0.1 "PUT /test.sh" 403   Forbidden

curl --user admin:123 -X MOVE http://127.0.0.1:5000/hello.sh -H "Destination: https://127.0.0.1:5000/hello.bak"                                     2023-09-18T12:36:35+03:00 INFO - 127.0.0.1 "MOVE /hello.sh" 403   Forbidden

and so on. List/download works, whereas upload/delete/move does not. Also checked cadaver, Total Commander for android.

**Log**
See above

**Environment:**
 - Dufs version: 0.36.0
 - Browser/Webdav Info: curl 8.2.1
 - OS Info: termux 0.118, android 8.0

**Comment by sigoden** [comment]
you should run `dufs -A -a admin:123@/:rw --auth-method basic`
The path requires `:rw` prefix to grant write permission.
