### ISSUE TITLE
Possible to resume downloads after Network Disconnect?

### ISSUE THREAD

**Issue by blackops786187** [sigoden/dufs#267]
**Problem**

Thanks for creating this simple tool. It has made sharing large files between people very simple.

As the title suggests, is it possible to resume a download after the server network has disconnected and the HTTPS connection has terminated. On chrome, when the disconnect happens, the browser marks the download as failed and clicking on resume doesn't seem to restart it from where it left off. Is this the normal behaviour for HTTP ? With SFTP, it has the capability to resume even after a complete termination of connection although i would like to use HTTP as the protocol since the speed doesnt suffer when the RTT is high and the file transfer is happening over the WAN

**Environment:**
 - Dufs version: 0.36.0
 - Browser: Version 116.0.5845.188  
 - OS Info: Windows 10 Pro 22H2 on Latest Patch as of 21/09/2023

**Comment by sigoden** [comment]
DUFS already supports resumable downloads, you can test it with:

```
curl --range 100-1099 http://localhost:5000/bigfile
```

**Comment by blackops786187** [comment]
Yes. I’m aware of that. Just wondering why chrome is able to resume it despite dufs supporting it. I can’t really ask a user to use curl to resume a download

**Comment by sigoden** [comment]
Everything is working fine in Chrome as well

![dufs](https://github.com/sigoden/dufs/assets/4012553/e649f7a9-926b-4821-bc92-48a2abeed5de)

**Comment by blackops786187** [comment]
Hi,

I belive i've located the issue behind my downloading failing to resume. It seems like using https whilst using untrusted certs prevents the resume of the download since it doesn't implicity trust the connection. I have rectified this although i am now seeing a different issue

If i use the basic auth switch, start the download and then cut the network off for a period of time, then reconnect it and attempt to resume the download, the chrome download manager flags the downloadd as failed and requiring authorisation despite not closing the browser. I would have assumed that basic auth stays cached whilst the browser is open so not sure whats going on here. 

Of course this issue doesn't manifest when i dont use any auth mechanism. I can record a video if it helps

**Comment by sigoden** [comment]
Resume download works on Basic Auth, fails on Digest Auth.

dufs can't do anything about it.

Note: The default auth method of Dufs is digest
