### ISSUE TITLE
A limited user shows root folder when using webdav

### ISSUE THREAD

**Issue by fimmspin** [sigoden/dufs#268]
I have an admin user with full access to / folder and a limited user with access only to /TEMP folder.

If connecting via web all is OK and showed correctly.

If connecting via Windows Webdav mapped drive using the limited user credentials i see the / root folder file listing and folders (there is really no access to file contents, resulting in a 401 or 403 error, correctly).

Would it be possible to set the /TEMP folder directly as / root when using the limited user credentials, as in the web version?

**Environment:**
 - Dufs version: 0.36.0
 - Browser/Webdav Info: Chrome/Windows 8.1 webdav
 - OS Info: Windows 8.1

**Comment by sigoden** [comment]
The awser is same to #263

Webdav must be designed like this.

This is because some webdav clients do not carry the Authorization header when listing files.
