### ISSUE TITLE
non-functional user button

### ISSUE THREAD

**Issue by laundmo** [sigoden/dufs#272]
**Problem**

There seeems to be a non-functional User button on the top right of the page. I can't click it, and the inspector shows no events attached to it.
![image](https://github.com/sigoden/dufs/assets/24855949/57c615db-cb06-4f64-bcfb-8f209fbb1454)

**Log**

not applicable

**Environment:**
 - Dufs version: v0.36.0 Docker
 - Browser/Webdav Info: Firefox
 - OS Info: Windows 10

**Comment by sigoden** [comment]
This button is used to mark that the user has logged in, the tooltip displays the username.

**Comment by laundmo** [comment]
That is very confusing. In every other web app a logo like that is used as a button, so maybe it would make sense to hust display the username directly?
