### ISSUE TITLE
The upload button is invalid on edge

### ISSUE THREAD

**Issue by KonpakuSyl** [sigoden/dufs#288]
**Problem**

The upload button is invalid on edge, but it work fine on firefox and chrome
Edge report this problem:
`Form elements must have labels: Element has no title attribute Element has no placeholder attribute`
`<input type="file" id="file" name="file" multiple="">`

**Environment:**
 - Dufs version: v0.37.1
 - Browser/Webdav Info:  Microsoft Edge 118.0.2088.76 arm64
 - OS Info: macos 13.1 m1

**Comment by sigoden** [comment]
If it weren't for your reminder, I wouldn't have noticed so many irregularities in the frontend. Thank you.
