### ISSUE TITLE
Upload button not selectable on Firefox 

### ISSUE THREAD

**Issue by sebastian-mora** [sigoden/dufs#290]
**Problem**

I can not select the upload button on Firefox (Version 119.0.1) on osx. I can upload files via Safari osx and mobile. 

This seems to be an issue with Firefox specifically 

**Log**

If applicable, add logs to help explain your problem.

**Environment:**
 - Dufs version: dufs 0.37.1
 - Browser/Webdav Info: Firefox Version 119.0.1
 - OS Info: macOS Monterey 12.6.5 
 - Dufs config

```
serve-path: '/my-path'
bind:
  - 127.0.0.1
port: 5000
auth:
  - admin:admin@/:rw
  - user:user@/
allow-upload: true
allow-delete: true
allow-search: true
allow-archive: true
```

**Comment by sigoden** [comment]
I cannot confirm the problem, can you provide a screenshot or console log?

**Comment by sigoden** [comment]
![dufs-03](https://github.com/sigoden/dufs/assets/4012553/74df1698-5ca0-4bf1-9fcb-36ec14a12004)

I have personally tested it on macOS using Firefox and did not encounter any issues; therefore, I am closing this issue.

If someone can provide more details about the issue, I will reopen it.
