### ISSUE TITLE
Support for Multipart ranges

### ISSUE THREAD

**Issue by 45gfg9** [sigoden/dufs#292]
## Specific Demand

I know this is a kinda niche feature, but `dufs` is already awesome, this would make it even more awesome.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests#multipart_ranges

## Implement Suggestion

Had a quick skim of the code. Need to do something to `handle_send_file()` I presume..

https://github.com/sigoden/dufs/blob/ae97c714d61ccb779726163c302a512abbe53838/src/server.rs#L722-L726

**Comment by sigoden** [comment]
Does this feature have any practical application scenarios?

Please give me a reason to be motivated to support this feature.

**Comment by sigoden** [comment]
Since there is no actual use case for multipart ranges, close this issue.

**Comment by sungdark** [comment]
test comment from bounty bot
