### ISSUE TITLE
about nginx proxy_pass

### ISSUE THREAD

**Issue by newdee** [sigoden/dufs#303]
hi, thanks for this dufs tools, 
I use nginx proxy_pass, and send to the dufs server, nginx config like this:
```
 location /file/ {
                #proxy_set_header X-Real-IP $remote_addr;
                #proxy_set_header HOST $http_host;
                proxy_pass http://192.168.100.210:25000/;
                #proxy_redirect off;
        }
```

but when I access the domain/file, it can not show the static  files correctly, such as the __dufs_v0.34.2_index.js not in domain/file/__dufs_v0.34.2_index.js but domain/__dufs_v0.34.2_index.js

so ,how should I proxy_pass it in nginx when  we access domain not on / path?

**Comment by sigoden** [comment]
try `dufs --path-prefix /file`

**Comment by newdee** [comment]
its ok, thank you ~
