### ISSUE TITLE
Search for a string in a file

### ISSUE THREAD

**Issue by evheniu** [sigoden/dufs#305]
## Specific Demand

Is it possible to add option for searching string in file and in result formed list of files where this string present ?

## Implement Suggestion

I mean like it works for examle with grep:
```
grep -rl --include=*.txt --include=*.TXT 'pattern'
```
pattern is the string for search, including formats for example .txt (maybe it's possible add to preconfig before instalation)

**Comment by sigoden** [comment]
No, I will not support this feature.

Searching for a string can be complicated, maybe you should look into services that specialize in this.
