### ISSUE TITLE
Authentication always returns 401 on Windows Explorer's network mount 

### ISSUE THREAD

**Issue by segln** [sigoden/dufs#307]
**Problem**
Password authentication always returns 401 on Windows Explorer's network mount and `net use` command.

Works well with web UI, Cyberduck, on Linux, etc.\
So it is not network/LAN/DNS/web server configuration issue.

Checked it in two Windows devices on both the version from 4 months ago and the latest version of Windows, including on Windows Sandbox.

Without authentication, it works well.

**Log**
```
INFO - 192.168.0.2 "OPTIONS /" 200
INFO - 192.168.0.2 "PROPFIND /" 401
INFO - 192.168.0.2 "PROPFIND /" 401
INFO - 192.168.0.2 "PROPFIND /" 401
INFO - 192.168.0.2 "PROPFIND /" 401
INFO - 192.168.0.2 "PROPFIND /" 401
INFO - 192.168.0.2 "PROPFIND /" 401
INFO - 192.168.0.2 "PROPFIND /" 401
INFO - 192.168.0.2 "PROPFIND /" 401
INFO - 192.168.0.2 "PROPFIND /" 401
INFO - 192.168.0.2 "PROPFIND /" 401
INFO - 192.168.0.2 "PROPFIND /" 401
```

It worked well before, not working after deprecation of `--auth-method`.

### Used command
`dufs ./data -A -a admin:password@/:rw`

`net use * https://example.com/ password /user:admin`

**Environment:**
 - Dufs version: 0.38.0
 - Browser/Webdav Info: Windows Explorer's network mount, `net use`
 - OS Info: Windows 11 Pro 22H2

**Comment by sigoden** [comment]
After pr #279 merged, dufs will set `www-authenticate` as follows:
```
www-authenticate: Digest realm="DUFS", nonce="6571013fd6b54c9f061bd40b9587721040", qop="auth", Basic realm="DUFS"
```
The `www-authenticate` contains two challenges: `Digest` and `Basic`. 

But  microsoft-webdav does not support www-authorize with multiple challenges. This has caused a problem.
Who would have thought that such a big company's products do not adhere to the HTTP standard.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate#syntax

![image](https://github.com/sigoden/dufs/assets/4012553/8884d07a-5191-40ea-a897-74f069366a2d)

**Comment by segln** [comment]
Well, they are Microsoft!

**Comment by bonjour-py** [comment]
still not working with windows 11 GUI. 
neither '添加一个网络位置' or '映射一个网络驱动器'
version 0.40
