### ISSUE TITLE
Option to download folders as tar

### ISSUE THREAD

**Issue by abe1242** [sigoden/dufs#308]
## Specific Demand

zip is really slow when sending large folders with multiple files, since it has to do compression.

Having an option to download as tar (without any compression like gz, bz xz, etc.) would be the better option.

**Comment by sigoden** [comment]
If only one compression format is supported, zip is the only choice. Because zip is the most versatile, the evidence is that windows can directly open zip, but other formats cannot.

Dufs is not prepared to support two compression formats, just like github has always only supported zip.

Dufs supports downloading compressed streams. The compression algorithm won't have a huge impact on download times. The biggest impact has always been bandwidth.

**Comment by abe1242** [comment]
In my case bandwidth is not the problem. I can send files using dufs with an average speed of 40 MB/s. Whereas, for a folder it around 6 MB/s. Tried to download the same folder with the .tar option in `miniserve` and I got close to 40 MB/s.

I do understand that the universal support of zip makes it a better default. You could implement tar by providing a flag like `--archive-format` which can be set to tar if needed, and by default it is set to zip.

**Comment by abe1242** [comment]
> The compression algorithm won't have a huge impact on download times. The biggest impact has always been bandwidth.

In my case bandwidth is not the problem. I can send files using dufs with an average speed of 40 MB/s. Whereas, for a folder it around 6 MB/s. Tried to download the same folder with the .tar option in `miniserve` and I got close to 40 MB/s.

> If only one compression format is supported, zip is the only choice. Because zip is the most versatile, the evidence is that windows can directly open zip, but other formats cannot.

I do understand that the universal support of zip makes it a better default. You could implement tar by providing a flag like `--archive-format` which can be set to tar if needed, and by default it is set to zip.

Correction: speed of zip is around 3.5 MB/s when I tested it right now.

**Comment by sigoden** [comment]
![image](https://github.com/sigoden/dufs/assets/4012553/0e133d8c-b998-490b-8cd0-7d2556456b3f)
The download speed of zip stream can reach 20M.
If there are many small files, the speed may be slower.

This speed is acceptable.

**Comment by abe1242** [comment]
My phone has the computing power of a potato so that explains the slow speed of zip. I guess I'm gonna have to stick to miniserve for sending folders and dufs for anything else.

Thanks for the response anyway

**Comment by sigoden** [comment]
#319 supports `--compress: none` which is similar to tar and is extremely fast. you may try it.

**Comment by abe1242** [comment]
Tried it on my PC and it works really well. Getting 170M+ speeds whereas with compression it is 20M. Haven't tried it on my phone, but I'm hoping it will be much faster than before.
Thank you so much for working on this. This was much needed
