### ISSUE TITLE
Serving all files from directory unzipped

### ISSUE THREAD

**Issue by ghost** [sigoden/dufs#309]
Im not sure if this is already possible, but downloading a folder contents without zipping.

basically, im currently quering for a list of directory items before downloading them concurrently, given that im storing only a few items in each directory at approximately 50kb, its likely not providing much of a boost to zip/send/unzip. I'm wondering if its possible to forego the list query and just download all from one request

**Comment by sigoden** [comment]
I don't understand what you mean.

Can you explain your needs with examples?

@timlagrande

**Comment by timlagrande** [comment]
I'm wondering if its possible to request all items in a directory unzipped, in one request. The current functionality suits my needs but I'm wondering how flexibly requests for a file are, for example, requesting a fileset via a path like /documents/*.pdf vs /documents/taxes.pdf

**Comment by sigoden** [comment]
There is no word called "directory unzipped".

>  for example, requesting a fileset via a path like /documents/*.pdf vs /documents/taxes.pdf
Do you mean to download files that match the search

**Comment by timlagrande** [comment]
Yes, currently you can download a zipped copy of the directory, I was wondering if individual files could be served "unzipped" or "uncompressed" or "not in zip format" in one request

**Comment by sigoden** [comment]
You want to manually select multiple files in the directory, and then download them in batches, with one file per download task.

Is this how I understand it?

**Comment by timlagrande** [comment]
Sure, but i was wondering if thats possible to do via one request, rather than concurrent requests

**Comment by sigoden** [comment]
No, the browser only supports downloading one file if you click on one link.
