### ISSUE TITLE
Access Control Bug

### ISSUE THREAD

**Issue by yx3016** [sigoden/dufs#315]
**Problem**

Access Control
Error encountered when configuring anonymous user access rules through the Configuration file!

**Log**
Windows
![image](https://github.com/sigoden/dufs/assets/81002806/82cc9727-af29-43ce-8b66-30978b532829)

Linux
![image](https://github.com/sigoden/dufs/assets/81002806/12136268-4308-4a45-a5d0-2980909c1ae2)

Config.yaml
![image](https://github.com/sigoden/dufs/assets/81002806/89398e72-b83b-4c14-a00e-55493ac287b3)

**Environment:**
 - Dufs version:0.38.0
 - Browser/Webdav Info: Chrome &　Edge
 - OS Info: Windows10 & Centos7.9

**Comment by sigoden** [comment]
see #306
