### ISSUE TITLE
Stopping ZIP file download breaks application

### ISSUE THREAD

**Issue by mowirth** [sigoden/dufs#318]
**Problem**

When Downloading the root directory as ZIP and then cancelling the download before it has started does result in a broken Pipe and renders the application unresponsive.

Steps to reproduce:
- Go to the root folder and click on the "Download as ZIP" Icon.
- Close/abort in the window when you are asked where you should store the file
- Reload page and see that dufs is unresponsive.

**Log**

```
Listening on:
  http://10.42.0.222:8080/
  http://127.0.0.1:8080/

2023-12-12T19:01:31Z INFO - 127.0.0.1 "GET /" 200
2023-12-12T19:01:35Z INFO - 127.0.0.1 "GET /?zip" 200
2023-12-12T19:01:52Z ERROR - Failed to zip /data, broken pipe
```

**Environment:**
 - Dufs version: latest
 - Browser/Webdav Info: Brave 1.6.0/Chromium 119
 - OS Info: macOS 14.1.2

Thank you in advance!

**Comment by sigoden** [comment]
Unable to reproduce the error.

https://github.com/sigoden/dufs/assets/4012553/0c22a743-39fd-43ac-9908-53b51c6b6871

**Comment by mowirth** [comment]
I checked again and it looks like the error only appears if you have a large file in this folder - in my case, the file is around 2,8GB big, dufs is running on kubernetes.

**Comment by sigoden** [comment]
Still unable to reproduce the error.

https://github.com/sigoden/dufs/assets/4012553/b8a8d1b5-a62b-4a0d-ab8c-14660251f3d5

**Comment by mowirth** [comment]
My apologies, it seems like the kubernetes port-forwarding cannot handle the broken stream and drops any further connections. I tested it with dufs locally and it works there.

Thank you for your help!
