### ISSUE TITLE
docker部署后使用http put上传文件的问题

### ISSUE THREAD

**Issue by HeiHeiHeMianMa** [sigoden/dufs#326]
windows下的Dufs没有问题，但是在ubuntu中用docker部署后使用http put上传文件
客户端没有收到返回，在文件正常上传完成十几秒后客户端抛出两条错误
Curl error 52: Empty reply from server
File upload failed: Received no data in response

**Comment by sigoden** [comment]
please paste dufs log. @HeiHeiHeMianMa

**Comment by sigoden** [comment]
why not follow the https://github.com/sigoden/dufs/issues/new?assignees=&labels=&projects=&template=bug_report.md
to submit the issue?

**Comment by HeiHeiHeMianMa** [comment]
> why not follow the https://github.com/sigoden/dufs/issues/new?assignees=&labels=&projects=&template=bug_report.md to submit the issue?

Sorry, I'm a newbie. I'll improve.

**Comment by HeiHeiHeMianMa** [comment]
> please paste dufs log. @HeiHeiHeMianMa

Log
log is normal
![Snipaste_2023-12-21_21-24-15](https://github.com/sigoden/dufs/assets/38659711/7bcebe98-93ee-4db1-81fb-a8e8430abdd8)

But I've already sorted out the issue, though I'm not sure why, after SetRequestHeader("Expect", "")

This is likely my fault.
Sorry to bother you., I've closed the issue
