### ISSUE TITLE
support upload a zip file and unzip it?

### ISSUE THREAD

**Issue by yafacex** [sigoden/dufs#341]
Indeed, I do need to upload a folder. However, it would be helpful if you could support uploading a zip file and extracting its contents to a specific folder.

**Comment by archandanime** [comment]
You can upload a folder by drag-dropping the directory to the web page, I tested and it worked.

**Comment by sigoden** [comment]
dufs cannot support unzipping an uploaded zip file, because it is error-prone.

1. There are various zip algorithms, which ones should be supported?
2. How to deal with file overwriting?
3. How to deal with hyperlinks in compressed files?
4. How to deal with path encoding?
...
