### ISSUE TITLE
Mobile device view?

### ISSUE THREAD

**Issue by tilllt** [sigoden/dufs#349]
Thanks for the app, works great...

some questions though

- the GUI is awfully small on a phone, is there a setting that i oversaw to choose a larger font size or enable a mobile optimized gui?

- are parallel uploads possible like with the tus protocol? (https://github.com/tus/tus-js-client)?

thanks

**Comment by sigoden** [comment]
1. I don't think it's necessary to refactor the mobile UI, if you feel the font is too small, you can zoom in. If you are still satisfied, you use custom UI with `--assets`.
2. dufs support resumable/partial uploads, also supports uploading several files in parallel.

**Comment by tilllt** [comment]
Thanks for the pointer with "--assets"!

I just tried running the docker and uploading a 1.5gb testfile, the server ran at 50-60% CPU under Docker Desktop / Windows on a i7-7700, is that normal or did i do something wrong?

**Comment by sigoden** [comment]
Many factors can affect CPU usage (docker, browsers, OS-releated processes and so on). You cannot draw any conclusion from the data.

You need to know dufs can run smoothly on some routers with less than 100M memory.
