### ISSUE TITLE
Can not use '@' in password.

### ISSUE THREAD

**Issue by 0400H** [sigoden/dufs#351]
if i use `Admin@123456` as password, it will can not login with `Admin@123456` but `Admin`.

start dufs with follow cmd:
```
dufs -b 0.0.0.0 -p 18000 -a admin:Admin@123456@/:rw --allow-upload --allow-search --allow-symlink --allow-archive /data
```

**Comment by sigoden** [comment]
I don't know what version of dufs you are using, but I checked the latest version v0.39.0 and found no problems. 

Please upgrade your dufs and try again.

**Comment by 0400H** [comment]
> I don't know what version of dufs you are using, but I checked the latest version v0.39.0 and found no problems.
> 
> Please upgrade your dufs and try again.

Upgrade v0.36.0 to v0.39.0 fixed it.
