### ISSUE TITLE
Can't upload file using davfs2

### ISSUE THREAD

**Issue by alive-corpse** [sigoden/dufs#354]
**Can't upload file using davfs2**

Hi! I've mounted shared resource via dufs with davfs2. Inside mount point I can create and remove directories, but I can't upload any file even with root permissions.

**Log**

$ dufs -A -a 'user:pass@/:rw'
Listening on:
  http://10.5.0.88:5000/
  http://10.11.11.234:5000/
  http://10.11.77.222:5000/
  http://127.0.0.1:5000/
  http://[::1]:5000/
    
# Below log lines that rises while I'm trying to upload file by copy into mounted point

2024-01-19T01:09:17+05:00 INFO - ::1 "PROPFIND /" 207
2024-01-19T01:09:17+05:00 INFO - ::1 "LOCK /issue" 404
.....

That's mounting with davfs
```
[1][00:50:10]evgeniy@vivo[~/mnt]$ sudo mount.davfs http://10.11.11.201:5000 disk
Please enter the username to authenticate with server
http://10.11.11.201:5000 or hit enter for none.
  Username: username
Please enter the password to authenticate user username with server
http://10.11.11.201:5000 or hit enter for none.
  Password:  
[0][00:50:16]evgeniy@vivo[~/mnt]$
[0][01:01:13]evgeniy@vivo[~/mnt]$ mount | grep localhost
http://localhost:5000 on /home/evgeniy/mnt/disk type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=16384,uid=0,gid=0,_netdev,helper=davfs)
[1][01:09:17]evgeniy@vivo[~/mnt]$ LC_ALL=en_US.UTF-8 sudo cp /etc/issue /home/evgeniy/mnt/disk/
cp: cannot create regular file '/home/evgeniy/mnt/disk/issue': No such file or directory
[1][01:10:33]evgeniy@vivo[~/mnt]$ LC_ALL=en_US.UTF-8 ls -lah /home/evgeniy/mnt/disk/issue
ls: cannot access '/home/evgeniy/mnt/disk/issue': No such file or directory
```

**Environment:**
 - Dufs version: dufs 0.39.0
 - Browser/Webdav info: davfs2 1.6.1-1 from official debian bookworm repo
 - OS info: MX Linux 23 based on Debian bookworm
 - Proxy server:  none

Have you any version builded with more verbose logging/debug? I can collect more logs.

**Comment by alive-corpse** [comment]
Sorry. I work with options use_locks 0, dav_group  davfs2, adding user to group davfs2 and mounting with parameters sudo mount.davfs -o uid=evgeniy,gid=evgeniy,user http://10.11.11.201:5000 /home/evgeniy/mnt/disk

**Comment by steadfasterX** [comment]
> use_locks 0

you saved my day, many thanks !
