### ISSUE TITLE
Add security policy and enable reporting

### ISSUE THREAD

**Issue by stevenengler** [sigoden/dufs#358]
This repository doesn't have any way to report security issues. My recommendation would be to add a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) and enable [vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository).

**Comment by sigoden** [comment]
Security policy was added, see https://github.com/sigoden/dufs/security

**Comment by stevenengler** [comment]
Thanks!
