### ISSUE TITLE
different operations for different users

### ISSUE THREAD

**Issue by jiangjiangflies** [sigoden/dufs#371]
I can add multiple users
`dufs -A -a admin:123@/ -a user:user@/`
But both admin and user have same all operations (delete, upload,etc). Is there a way that only admin have all the operations while other users can only browser files?

**Comment by sigoden** [comment]
![image](https://github.com/sigoden/dufs/assets/4012553/4547eb7a-d75a-47b3-9a2c-833c08f27b35)

`-a admin:123@/` grants admin only read-only permissions, `-a admin:123@/:rw` to grants admin all permissions.

**Comment by jiangjiangflies** [comment]
Sorry, the **Advanced topics** is folded in the README. I didn't notice that. Thank you!
