### ISSUE TITLE
I would like to provide an API that returns the hash value of a file

### ISSUE THREAD

**Issue by ldeng76** [sigoden/dufs#373]
## Specific Demand
I would like to provide an API that returns the hash value of a file, which is important to verify that the file has been uploaded successfully.

## Implement Suggestion
no

**Comment by sigoden** [comment]
Make sense, use `GET /path-to-file?hash` to returns the shas256 hash value of a file.

```sh
$ curl localhost:5000/myfile1?hash

d09fd4af745c71fcc13c1e2c9783845c46aa19086bf450f330a89e5de98a69be
```
