### ISSUE TITLE
windows下webdav添加文件和修改文件错误

### ISSUE THREAD

**Issue by hw2411** [sigoden/dufs#380]
**Problem**

windows下使用webdav添加网络驱动器后，无法添加文件和修改文件

**Configuration**

启动命令：dufs.exe -A -a test:test123@/:rw --auth-method basic   （去掉auth-method也是同样错误）

可以正常浏览打开删除文件，但是无法拷贝文件到网络驱动器或者修改网络驱动器里的文件。

但是使用 dufs.exe -A 网络驱动器文件操作均正常。

**Log**

拷贝文件到网络驱动器出错时console截图：
![1715075197752](https://github.com/sigoden/dufs/assets/9170983/62e53de0-908c-4d30-967a-da7af6f92db8)

**Environment:**
 - OS info:windows

**Comment by hw2411** [comment]
1

**Comment by hw2411** [comment]
2

**Comment by hw2411** [comment]
1212

**Comment by hw2411** [comment]
test

**Comment by sigoden** [comment]
Please use the latest version of dufs (--auth-method have already been abandoned)
Please mark the logs you think are releated to bug. （The logs look fine. 401 is for authentication)
@hw2411

**Comment by hw2411** [comment]
> Please use the latest version of dufs (--auth-method have already been abandoned) Please mark the logs you think are releated to bug. （The logs look fine. 401 is for authentication) @hw2411

@sigoden  thinks a lot, I'm already using the latest version of dufs and not using the auth-method parameter, but the problem persists. The first image below shows the output of the console when I boot directly with dufs -A and there is only one file copy action in the Windows folder. I don't know why there were two puts, but both of them worked, and the file was copied successfully. The second image shows the output of the console when I started the service with dufs -A -a with authentication and there was only one file copy action in the Windows folder. There are also two PUT operations, the first PUT operation succeeds, and the second PUT operation fails (there is no 201 status code below the 401 status code).This is followed by a successful delete operation (possibly a rollback of a Windows file operation).

dufs -A log(can copy file):
<img width="662" alt="image" src="https://github.com/sigoden/dufs/assets/9170983/8c6eabf5-322b-4851-b86c-d99857f3d75c">

dufs -A -a log(can not copy file):
<img width="651" alt="image" src="https://github.com/sigoden/dufs/assets/9170983/c460f121-6e9b-4165-a510-7240306b4bb4">

**Comment by hw2411** [comment]
@sigoden thx a lot
