### ISSUE TITLE
PROPFIND method support infinity depth

### ISSUE THREAD

**Issue by xiaozhuai** [sigoden/dufs#387]
## Specific Demand

PROPFIND methid can provide a `depth` parameter in the header,  it accept `0`, `1`, `infinity`:
* 0: Retrieve properties of the directory
* 1: as 0 + properties of all files in the directory
* infinity: as 1 + properties of all files in sub-directories of the directory (recursively)

Please support infinity depth.

**Comment by sigoden** [comment]
Are there any common usage scenarios for this feature?
dufs is a lightweight web server and does not promise to support all webdav specifications (for example, it does not support lock/unlock).
This feature can have a significant impact on server performance. 
We are not prepared to support if it is not necessary. hope you can understand.

**Comment by xiaozhuai** [comment]
> Are there any common usage scenarios for this feature?

I use dufs as cache server for vcpkg. But as time goes by, more and more files will be cached, taking up more and more space. So I need to clean cache regularly.
This requires being able to list all files in a directory. 

Of course, I could propfind one directory at a time and call it recursively until I get all the files.
But the problem is that there are a large number of requests between the client and the server.
If infinity depth is supported, the result can be obtained in one request.

> This feature can have a significant impact on server performance.
We are not prepared to support if it is not necessary. 

I understand. I wonder if we could make this an optional `allow-propfind-infinity` feature?
This feature is actually very important for those who need to list files recursively.

**Comment by xiaozhuai** [comment]
I switch to nginx, it also didn't support propfind infinity. 
And I've update my script, now it support list files in parallel.
Total file count is 1435.
Here is a benchmark result. The parallel num is 1, 4, 8, 32.

## Nginx
<img width="571" alt="image" src="https://github.com/sigoden/dufs/assets/4773701/a07b685d-d996-407d-a23d-6ad74982c0ee">

## dufs
<img width="570" alt="image" src="https://github.com/sigoden/dufs/assets/4773701/032d686d-71d8-4629-a95a-7c7976a09955">

**Comment by xiaozhuai** [comment]
Here is the code snippets I use to get files recursively
```js
    async readdir(dir) {
        const files = await this.client.getDirectoryContents(dir); // Perform PROPFIND request with depth = 1
        const subFiles = await Throttle.all(files
            .filter(file => file.type === 'directory')
            .map(file => async () => {
                return await this.readdir(file.filename);
            }), {maxInProgress: 8});
        return files.concat(...subFiles);
    }
```
