### ISSUE TITLE
Disk usage analysis

### ISSUE THREAD

**Issue by red-avtovo** [sigoden/dufs#393]
## Specific Demand

I'm already enjoying the app, but I would be happy to have the ability to clear the space hassle-free, and I only see a solution similar to DaisyDisk or Filelight to be able to see my directories as a sunburst map for a more accessible overview and directory deletion.

## Implement Suggestion

Implement a separate page with the sunburst map where directory name and size would be displayed with options to change the root directory to display the map or delete the selected directory.

A visual example:
![image](https://github.com/sigoden/dufs/assets/10682826/2a34dcd0-7ac7-4d7a-a773-cca0ec76ba17)

**Comment by sigoden** [comment]
This feature is beyond the scope of dufs's responsibilities.

Sorry, we will not support this feature.
