### ISSUE TITLE
ghcr container image 

### ISSUE THREAD

**Issue by bonjour-py** [sigoden/dufs#394]
## Specific Demand

Docker Hub is unavailable in certain locations.
need container image in ghcr （github packages） or somewhere else

**Comment by sigoden** [comment]
We will not support this feature.

Docker is and still is the leading image repository.

**Comment by bonjour-py** [comment]
@horizon0514 @jessehu  国内有关docker hub 的所有访问都断了  请考虑ghcr

**Comment by bonjour-py** [comment]
> We will not support this feature.
> 
> Docker is and still is the leading image repository.

please! it will shows on here https://github.com/sigoden?tab=packages

**Comment by bonjour-py** [comment]
and i can do this work

**Comment by bonjour-py** [comment]
https://github.com/sigoden/dufs/pull/396

**Comment by bonjour-py** [comment]
what about here   https://gallery.ecr.aws/docker?page=1  where docker official will Repeatedly push images
