### ISSUE TITLE
Version 0.41 can't run on Win2008R2 server

### ISSUE THREAD

**Issue by fimmspin** [sigoden/dufs#395]
Version 0.40 worked ok (dufs-v0.40.0-i686-pc-windows-msvc.zip), but the new version 0.41 can't start.

Has something changed about requirements, different compile options or different minimum VCC version?

Tried both i686 version (that I always used, until 0.40) and also the x86_64 version, but with no success.

**Comment by coflery** [comment]
The same situation,
Version 0.41 work bad on Windows7x64:

![image](https://github.com/sigoden/dufs/assets/13827813/c2b35bc3-e86c-4867-ad8c-f5b1faa9076d)

**Comment by sigoden** [comment]
Sorry, dufs cannot run on Windows 7. There's no solution for this issue in the short term. I'll continue to look into it and hopefully find a solution.
