### ISSUE TITLE
Speed Limiter

### ISSUE THREAD

**Issue by blackops786187** [sigoden/dufs#401]
Hi,

Thanks for the work youve put into this file server. Sharing file securely has become a breeze !

Was wondering how feasible it would be to implement the ability to specify a rate limit via command line argument. This would be helpful when you dont want users to max out your upload when they are downloading files from you and therfore saturate your connection and cause issues

Sounds simple in theory but i suspect its not straightforward to implement. If its not an option for you, can you suggest other tools to rate limit

**Comment by sigoden** [comment]
Dufs will not support this feature.
