### ISSUE TITLE
Please allow creating files by POST method. Sometimes it is impossible to use the PUT method

### ISSUE THREAD

**Issue by benziout** [sigoden/dufs#404]
## REQUEST
POST http://192.168.1.10/file.txt HTTP/1.1
Content-Length: 5
Host: 192.168.1.10

Hello

                 ## ERROR RESPONSE
HTTP/1.1 405 Method Not Allowed
access-control-allow-origin: *
access-control-allow-credentials: true
access-control-allow-methods: *
access-control-allow-headers: Authorization,*
access-control-expose-headers: Authorization,*
content-length: 0
date: ...

**Comment by sigoden** [comment]
we will not support this feature. Because `POST` does not conform to the webdav specification,

If it is impossible to use the PUT method, you should avoid use dufs api.
