### ISSUE TITLE
about webdav service

### ISSUE THREAD

**Issue by CJSen** [sigoden/dufs#406]
-- dufs version： 0.41.0
When I use Alist to connect to the services provided by dufs, the storage connection method used is webdav. I found that after I clicked download, I failed to trigger the browser's download function correctly, but opened the file in a new tab, such as a txt file(mp3, mp4,pdf and so on).But the storage connection method used is sftp, it is ok.
<img width="935" alt="image" src="https://github.com/sigoden/dufs/assets/48038717/9d37ca06-c8d4-40e3-8880-41f0e34895d5">
After checking the relevant requests, I found that it was caused these mistakes.
<img width="1301" alt="image" src="https://github.com/sigoden/dufs/assets/48038717/bd8a7442-e6ab-4c2a-a02c-2a1853bcda60">
I'm using wget can be downloaded normally, but when I access it directly using IP: port/links, I also open a tab instead of downloading.
eg: wget 192.168.1.1:5000/books/test.txt    It downloads normally.
open links:192.168.1.1:5000/books/test.txt in browser, It can't download normally, but opens the file in the browser.
If this is normal, please close this issue

**Comment by sigoden** [comment]
This is a feature of modern browsers. They can handle a wide range of file types natively, meaning they can open and display them right within your browser window or a new tab. These file types commonly include:
* **Web Pages:** HTML, PHP, ASP, etc.
* **Images:** JPG, PNG, GIF, SVG, etc.
* **Documents:** PDF, TXT, sometimes DOCX/XLSX/PPTX (depending on browser extensions)
* **Audio & Video:** MP3, MP4, WAV, WebM, etc.
