### ISSUE TITLE
not use webdav

### ISSUE THREAD

**Issue by wqiucheng** [sigoden/dufs#408]
Hello developer, I don't want to use the webdav function when using a static page. Which command parameter should I use?

**Comment by sigoden** [comment]
@wqiucheng

Run `dufs` without any `--allow-*` options.

**Comment by sigoden** [comment]
WebDAV is not returning any new data. The key is avaiable operations and access control.

For example, `GET /` returns html, `PROPFIND /` returns xml. They are essentially the same.

You need to configure the dufs based on your own needs. It's pointless to worry about whether it enables WebDAV.
