### ISSUE TITLE
cannot partial update using ranges beyond the current file size

### ISSUE THREAD

**Issue by fyears** [sigoden/dufs#414]
**Problem**

In [this pr](https://github.com/sigoden/dufs/pull/343) dufs supports partial upload from sabre style. But it seems that currently dufs cannot accept ranges **beyond** the the current file size.

Steps to reproduce:

1. Create a 0-byte file using put. Everything is ok.
2. Append a few bytes to that file, using patch with `X-Update-Range: append`. Everything is ok, too.
3. Append a few bytes to that file, using patch with `X-Update-Range: bytes=3-6`, **where the start offset is larger than  the current uploaded file size**. The server returns an error 400.

I think the problem may be because that dufs doesn't implement this rule from [sabre/dav](https://sabre.io/dav/http-patch/):

> If the start-byte is beyond the file's current length, the space in between will be filled with NULL bytes (0x00).

**Configuration**

Nothing special

```
dufs -A --enable-cors --bind 0.0.0.0 --port 8080
```

**Log**

```
2024-07-14T00:01:48+08:00 INFO - 192.168.31.198 "PATCH /xxx.pdf" 400
```

**Environment:**
 - Dufs version:0.41.0
 - Browser/Webdav info: I use the js webdav client library https://github.com/perry-mitchell/webdav-client
 - OS info: Windows
 - Proxy server:  No

**Comment by sigoden** [comment]
Can you explain why you need this?

**Comment by fyears** [comment]
For example, I would like to upload a file by chunks in parallel.

If only `append` is supported, I can only upload the chunks one by one is sequences.

If ranges beyond file size is supported, I can: create 0 byes file using put, then upload **last byte (or chunk)** using range, then upload the remaining chunks in parallel.

**Comment by sigoden** [comment]
We will not support partial update using ranges beyond the current file size. Here is the reason:

1. Dufs is stateless, it cannot implement parallel writing to the same file, Therefore, it cannot implement uploading a file by chunks in parallel. 

2. Too dangerous. A malicious large range value (1000000000000000-1000000000000001) could exhaust your disk resources. Normally, the malicious user need to upload this much data, but now only need 1 byte.

**Comment by fyears** [comment]
OK. But here is another related point:

By returning the header `sabredav-partialupdate` but dufs doesn't fully support everything in https://sabre.io/dav/http-patch/ . So it may confuse the automated detection of some program like mine. 

Is there any other special header indicating the server is dufs so that my program and potentially other program can differentiate dufs from other normal sabre/webdav servers?

**Comment by sigoden** [comment]
Thanks for your reminder.

**Comment by fyears** [comment]
Ok. May I ask when will the new version be released?

**Comment by sigoden** [comment]
A new version is generally released every 3 months unless there are significant updates. So the next update will have to wait until the end of August.
