### ISSUE TITLE
how could I use auth with docker？

### ISSUE THREAD

**Issue by charklaliu** [sigoden/dufs#432]
使用docker的话，想要增加账号密码验证，要怎么做？

**Comment by sigoden** [comment]
see readme.

![image](https://github.com/user-attachments/assets/4a716508-0a86-4d89-8863-030e72362eba)

- DUFS_AUTH
- --config config.yam
- --auth

**Comment by charklaliu** [comment]
![image](https://github.com/user-attachments/assets/ed31de59-c832-4f6f-9c27-d507beb7a049)

我看了readme，但是还是不太会用，因为我是用docker的命令行去执行的
