### ISSUE TITLE
Suggestion: Drag n drop to download

### ISSUE THREAD

**Issue by ilia-21** [sigoden/dufs#435]
## Specific Demand

If you drag n drop any direct link to a file into a folder on your system, browser will download file from to that folder. Example: "raw" button in github. This is very useful as it eliminates the need to select a folder when downloading. I would like to have this option in dufs.

## Implement Suggestion

Make these links dragable 
![image](https://github.com/user-attachments/assets/162cf051-1235-43f2-a4e4-35c18960ecd2)

**Comment by sigoden** [comment]
@ilia-21 

I don't understand your request. Could you provide a demonstration video?

**Comment by ilia-21** [comment]
Sure! 

https://github.com/user-attachments/assets/30d2315e-dea4-487c-abd0-486cc05934da

I remember this working on windows too

**Comment by sigoden** [comment]
@ilia-21 

It's just a feature of the file browser itself. I've tried it on both LinuxMint and Windows, but it didn't work. It only generated an HTML link.

Have you tried dufs links? I don't think they are much different from GitHub raw links? Both can be clicked to open source files in a browser.

**Comment by ilia-21** [comment]
Yes, I tried dufs links, but they don't drag at all. When I try to drag them, they don't do anything, as if dragging is disabled in the code. 
Just to clarify: the problem is not "I'm dragging, but files are not downloading", the problem is "Links are not dragable"

**Comment by sigoden** [comment]
@ilia-21 

How your tried text file like `.md` or `.txt` ? Maybe the file format matter.

**Comment by ilia-21** [comment]
Yes, I tried, none of the links are dragable. 
Question: are they dragable on your side? Can you repeat the same as I showed with "raw" button in dufs, even if it only generates HTML link? If yes that means the problem is on my side

**Comment by sigoden** [comment]
This function is not universal and doesn't even work properly in Windows.

https://github.com/user-attachments/assets/387e12d4-a519-494f-bce4-2d45b7d2673a

> EDIT: I tested myself, and removing dragstart on this line makes links dragable, also suggested feature works as expected

I have no way to confirm the effect. If it's just removing `dragstart`, you can submit a PR.
