### ISSUE TITLE
Seperate upload and delete permissions

### ISSUE THREAD

**Issue by bonsairobo** [sigoden/dufs#441]
## Specific Demand

I want to specify ACLs using seperate "upload" and "delete" permissions. This would allow me to have users that can upload to a directory without deleting anything.

## Implementation suggestion

I think the simplest option would be to split the `w` permission into `c` and `d`, for create and delete. This could maintain backwards compatibility by making `w` imply `cd`, but something like `rc` would only imply read and create, not delete.

This scheme is a bit different from how the existing ACLs work though. As I understand it, there is only `ro` and `rw`. So `o` does not mean anything on its own. There might need to be specific handling of that for backwards compatibility.

Another point worth considering is whether update and create should have separate permissions. Update also has the capacity to be destructive like a delete, just by overwriting a file with an empty byte array.

**Comment by sigoden** [comment]
With `Upload without delete`, you might encounter situations where incorrectly uploaded files cannot be deleted, and interrupted uploads can neither be resumed nor removed.

**Comment by bonsairobo** [comment]
AFAICT my only way to work around this is to have separate accounts and home directories for every user. Is it possible to update the dufs config file without restarting the service? This would let me build a dynamic user management service on top of dufs.

**Comment by sigoden** [comment]
No plan

**Comment by bonsairobo** [comment]
No plan to support config updates?

**Comment by sigoden** [comment]
There's no plan to watch the configuration file for changes and restart the service.

This complicates things considerably without offering much benefit.
