### ISSUE TITLE
**not bug, need help**

### ISSUE THREAD

**Issue by LhymeFruit** [sigoden/dufs#443]
heavy apologies for using a bug report, i need help with the authentication args
I have a directory that a public/anon user has assess to and I have an admin account with assess to everything
however the admin account doesn't have assess to said public directory. Is it possible to allow the admin account to the public directory?
my launch args are this (censored for privacy and replaced logins)
sudo docker run -v `pwd`:/data -p *censor* --rm sigoden/dufs /data -A -a admin:password@/:rw -a @/ro,/(public dir)/ 

Im pretty sure i can use curl to access the pub dir on the admin account but id rather make it so that i can access it on the web interface .

**Comment by sigoden** [comment]
`-a admin:password@/:rw` give admin perms to access any directory, Whether it's using `curl` or the webui.

**Comment by LhymeFruit** [comment]
> `-a admin:password@/:rw` give admin perms to access any directory, Whether it's using `curl` or the webui.

seems as if the browser just assumes im switching to the guest account or something, any help with that? every time i load into the pub directory it doesnt let me upload. it also doesnt let me relocate files from any directory to the public directory

**Comment by sigoden** [comment]
Do you see a `login` button in the top-right corner? Please log in to the admin account; then, you can see all the directories.

**Comment by LhymeFruit** [comment]
> Do you see a `login` button in the top-right corner? Please log in to the admin account; then, you can see all the directories.

![image](https://github.com/user-attachments/assets/3cc8770d-30e6-4703-b5cd-839c830423f4)
if its this button it just says "Forbidden"

**Comment by sigoden** [comment]
Please refer to the [bug_tempalate](https://github.com/sigoden/dufs/issues/new?assignees=&labels=&projects=&template=bug_report.md) to post your configuration, logs or screenshots. Without this information I can't help you.

**Comment by LhymeFruit** [comment]
> Please refer to the [bug_tempalate](https://github.com/sigoden/dufs/issues/new?assignees=&labels=&projects=&template=bug_report.md) to post your configuration, logs or screenshots. Without this information I can't help you.

**Problem**


--
**Configuration**


sudo docker run -v pwd:/data -p censor --rm sigoden/dufs /data -A -a admin:password@/:rw -a @/ro,/(public dir)/


**Log**



**Environment:**
 - Dufs version:0.41.0
 - Browser/Webdav info:Firefox 129.02
 - OS info:windows 10 22h2
 - Proxy server:  none

**Comment by sigoden** [comment]
MIssing log？How do I figure out why I'm getting the `Foriden` error?

Also, Are you really passing the argument `-a @/ro,/(public dir)/`? Do the directories `/ro` and `,/(public dir)` actually exist?

**Comment by LhymeFruit** [comment]
> MIssing log？How do I figure out why I'm getting the `Foriden` error?
> 
> Also, Are you really passing the argument `-a @/ro,/(public dir)/`? Do the directories `/ro` and `,/(public dir)` actually exist?
both directories exist. and how would i get the log from firefox?

**Comment by LhymeFruit** [comment]
> MIssing log？How do I figure out why I'm getting the `Foriden` error?
> 
> Also, Are you really passing the argument `-a @/ro,/(public dir)/`? Do the directories `/ro` and `,/(public dir)` actually exist?

It also worked perfectly fine before I removed the credentials from the anon account. the login used to be guest:guest
