### ISSUE TITLE
support/integrate tus upload

### ISSUE THREAD

**Issue by LeiYangGH** [sigoden/dufs#452]
## integrate tus upload

dufs is easy to deploy and use, thanks for such great product!
meanwhile, when I first deployed it and reverse proxied using nginx and tried to upload a 2M size file, it failed with error like 'entity too large'.
I changed the nginx config extending the size limit then can upload now.
I searched around the issues and found many complain about resumable uploads or big file uploads, or feature requests about  avoid uploading same file, while almost all not solved and just explained some reasons.
I went over the source code as well as explainations in some jiras and am sure the upload is streaming, maybe the default chunk size is more than 2M? I didn't find any configuration on chunk size in the readme.

## Implement Suggestion

I have experience of using another open source upload component called [tus](https://tus.io/), which solves all the issues metioned above, and the official server also written in go. It even has public [protocol](https://tus.io/protocols/resumable-upload) dedicated to solve this problem. 
So suggest integrated tus at protocal level(for example, copy some source code from [tusd](https://github.com/tus/tusd), or at application level, add option to support listening tusd upload events at some endpoint.

I have little experience with go programming, and not know the effort/possibility, could you consider it, thanks!

**Comment by sigoden** [comment]
We will not support this feature.

**Comment by LeiYangGH** [comment]
because that tus doesn't have web page and access control built in.

**Comment by wrenix** [comment]
That is sad, tus as an well defined protocol is implemented in several client libraries.
