### ISSUE TITLE
如何让mkv文件在浏览器直接播放，而不是下载

### ISSUE THREAD

**Issue by carlsue** [sigoden/dufs#454]
如题。如何让mkv文件在浏览器直接播放，而不是下载。
我看了下https://github.com/sigoden/dufs/tree/main/assets/index.js       其中const IFRAME_FORMATS =可以添加后缀，是不是添加重新编译就可以了呢？

**Comment by sigoden** [comment]
No, modern browsers like Chrome don't natively support the MKV (Matroska) video format.

**Comment by ElTopo** [comment]
@carlsue With chrome/edge, you can install "Media Player" addon, and then right click on .mkv file link, use "Play with Media Player", the .mkv will be played in a browser window (if Media Player addon has proper codec).

See:
https://chromewebstore.google.com/detail/mediaplayer-video-and-aud/mgmhnaapafpejpkhdhijgkljhpcpecpj?snuoi&pli=1

**Comment by carlsue** [comment]
> @carlsue With chrome/edge, you can install "Media Player" addon, and then right click on .mkv file link, use "Play with Media Player", the .mkv will be played in a browser window (if Media Player addon has proper codec).
> 
> See: https://chromewebstore.google.com/detail/mediaplayer-video-and-aud/mgmhnaapafpejpkhdhijgkljhpcpecpj?snuoi&pli=1

it's working,thanks!
