### ISSUE TITLE
First element is hidden by the search bar

### ISSUE THREAD

**Issue by ign0tus** [sigoden/dufs#456]
**Problem**

In the mobile view, the first element is hidden by the search bar in the case of long paths.

**Screenshots/Media**

- Desktop site
![photo_2024-09-12_16-59-26](https://github.com/user-attachments/assets/0b20838d-e779-4859-a584-56c0acc74cfa)

- Mobile site
![photo_2024-09-12_16-59-23](https://github.com/user-attachments/assets/e7878cd2-4d17-4829-bb80-b1dedec9046a)

**Environment Information**
 - Dufs version: 0.40.0
 - Browser/Webdav info: Chrome + Mull
 - OS info: Android 14 (Pixel 6a)
 - Proxy server (if any): Caddy Reverse-Proxy

**Comment by sigoden** [comment]
Already fixed in #386, please upgrade dufs to latest version.
