### ISSUE TITLE
Add a feature to serve any file as text/plain in the browser

### ISSUE THREAD

**Issue by tkapias** [sigoden/dufs#458]
## Specific Demand

Can you add a button in the web interface, like the edit button, which would force to display any file as text/plain in a new browser tab?

- It need to override browser internal mimetype features.
- It should be disabled for binary files.
- Would be nice if it could be called directly like `https://dufs.example.com/path/file.ext?plain`.

### Context

Before Dufs, I had too many file servers (seafile, privatebin, syncthing, kopia...). I got ride of seafile and I would like to replace privatebin's usage by dufs too.

The main issue is that sometime I would like to display some content in the browser with syntax highlighting.

For plain files, it 's pretty easy:
  - Files with a mimetype text/plain are displayed as text in Firefox.
  - I use the addon [Enlight](https://github.com/Qeole/Enlight) to apply coloration.

But, there are 2 issues:

  - Until recently Firefox did not display all `text/*` types, some of them where pushed for download. Even markdown's `.md` were like that.

Apparently, Firefox's release 128 changed that: [bugzilla-1319262](https://bugzilla.mozilla.org/show_bug.cgi?id=1319262), [bugzilla-196078](https://bugzilla.mozilla.org/show_bug.cgi?id=196078). But it will take some time to get this on Firefox ESR.
I tried to force mimetypes in nginx, but apparently Firefox ultimately parse the extension.
```nginx
types        { text/plain txt md log; }
default_type text/plain;
```

  - Even if all `text/*` mime types are considered as plain in Firefox, there are other filetypes that a user would like to view, and there are also other browsers with the same issue.

## Implement Suggestion

Not sure.

Maybe use js to serve the file with a fake extension and mimetype by appending `.plain` to it?

But testing binary files probably needs to be done server-side.

**Comment by tkapias** [comment]
I just saw that you can get the editor to display the file content  with `?view` (without edition toolbar) and that it does check for binaries or large files.

It's really close to what I requested.

## New Sugestion

- Create a new parameter `?plain`.

Differences with `?view`:

  - Open in a new tab.
  - Make `class="editor-page"` the only element in the body.
  - Maybe disable the editing feature for this view.

- Add 2 new buttons for "View file" and "View plain file", near the "Edit file" in the index.

**Comment by sigoden** [comment]
We will not support this feature. This demand is too niche.

To display the file in the browser with syntax highlighting, you should use browser extensions.

**Comment by tkapias** [comment]
You were right not to work on it, after your message I found a combination of Firefox extensions that works.

I just leave the comment for other users.

You can force the conversion of any content-type to text/plain with the [Content-Type Fixer](https://addons.mozilla.org/en-US/firefox/addon/content-type-fixer/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) extension.
Most content-type in text/* should already open inline after Firefox 128, but I use ESR and it's not the case, also sometime you may want to display some application/* contents like vcards.
This means that when opening the link to a markdown or vcard file, you can force it to display inline in Firefox instead of saving it.

Then, you can use the [Enlight](https://addons.mozilla.org/en-US/firefox/addon/enlight/) extension to add syntax highlighting to the inline text.

Thanks for Dufs, it's a good tool.
