### ISSUE TITLE
Add an authorization token after the link

### ISSUE THREAD

**Issue by 52funny** [sigoden/dufs#462]
## Specific Demand

I have a requirement that I need to use IINA to open a video on a web page in authentication mode, but IINA may not have the authorization to get the token, so I can't open the video.

<img width="1170" alt="image" src="https://github.com/user-attachments/assets/bfb6bd8f-76ee-488b-8399-6a35fe69950d">
<img width="640" alt="image" src="https://github.com/user-attachments/assets/aca72910-69ad-4f33-91c3-5eb9c2009774">
<img width="249" alt="image" src="https://github.com/user-attachments/assets/480fb5cd-4a2e-472b-8ee5-9f6250d402fd">

## Implement Suggestion

Is it possible to add a token for authentication after the resource link?

Like this:
```
https://192.168.1.2:5000/space/downloads2/Pulp.Fiction.1994.UHD.BluRay.2160p.DTS-HD.MA.5.1.DV.HEVC.REMUX-FraMeSToR/Pulp.Fiction.1994.UHD.BluRay.2160p.DTS-HD.MA.5.1.DV.HEVC.REMUX-FraMeSToR.mkv
===>
https://192.168.1.2:5000/space/downloads2/Pulp.Fiction.1994.UHD.BluRay.2160p.DTS-HD.MA.5.1.DV.HEVC.REMUX-FraMeSToR/Pulp.Fiction.1994.UHD.BluRay.2160p.DTS-HD.MA.5.1.DV.HEVC.REMUX-FraMeSToR.mkv?token=xxxxxx
```

**Comment by sigoden** [comment]
We will not support this feature.

Maybe you can achieve this requirement through custom UI.

![image](https://github.com/user-attachments/assets/94bccfac-ef61-4176-b646-4d835260c035)
