### ISSUE TITLE
Download .zip even if directory is empty

### ISSUE THREAD

**Issue by SourLemonJuice** [sigoden/dufs#463]
## Problem

The zip file can be downloaded even if the current directory is empty.
This should be a minor issue

## Configuration

```
# compose.yaml
command: /data -A -a admin:admin@/:ro -a @/:ro
```

## Environment Information

 - Dufs version: v0.42.0
 - Browser/Webdav info: Firefox and Edge
 - OS info: Docker
 - Proxy server (if any): Nginx

**Comment by sigoden** [comment]
We don't think there's anything wrong with that.

The zip command can also create a zip file from an empty directory.
```
mkdir test-dir
zip -r test-dir.zip test-dir
```
