### ISSUE TITLE
Overwriting old files doesn't prompt

### ISSUE THREAD

**Issue by wxf2288** [sigoden/dufs#464]
When the user has upload and delete permissions, uploading files in the browser will automatically overwrite the old files without any prompt.

**Comment by sigoden** [comment]
Specifically designed this way.

Can you imagine a situation where you upload an entire directory, possibly containing hundreds of files, and you have to confirm each one individually? Would you be okay with that?

**Comment by wxf2288** [comment]
Ok thanks!
