### ISSUE TITLE
设置账户后 下载 401 安卓浏览器

### ISSUE THREAD

**Issue by SoulLinkIly** [sigoden/dufs#465]
我在openwrt上使用dufs，在win10电脑上下载文件没有问题，服务器显示使用了账户下载，但是我想要使用手机的安卓浏览器下载时，显示失败，服务器显示先有一个账户下载请求200通过，手机提示可以下载，点击下载，服务器显示有一个空账户新建链接并返回401，我使用电脑浏览器f12工具发现登陆账户储存在请求头authorization中
Digest username="lchsnas", realm="DUFS", nonce="6714c2b6830416c71f2915357f2c3a7d89", uri="/nas/dianying/%E5%A4%A7%E8%AF%9D%E8%A5%BF%E6%B8%B8%E4%B9%8B%E6%9C%88%E5%85%89%E5%AE%9D%E7%9B%92.1995.mkv", response="03b3b3abee9a69fafc8def19513eb59f", qop=auth, nc=00000008, cnonce="634efe858a70adcd"
是不是安卓浏览器新建下载链接时没有带请求头，导致下载失败？这能修复吗？
2024-10-20T08:58:15Z INFO - "IPv6" lchsnas "GET /nas/dianying/%E5%A4%A7%E8%AF%9D%E8%A5%BF%E6%B8%B8%E4%B9%8B%E6%9C%88%E5%85%89%E5%AE%9D%E7%9B%92.1995.mkv" 200
2024-10-20T08:58:17Z INFO - "IPv6" - "GET /nas/dianying/%E5%A4%A7%E8%AF%9D%E8%A5%BF%E6%B8%B8%E4%B9%8B%E6%9C%88%E5%85%89%E5%AE%9D%E7%9B%92.1995.mkv" 401
-a lchsnas:123@/nas:rw --log-format '$remote_addr $remote_user "$request" $status' 使用了这个

**Comment by sigoden** [comment]
I have tested it on Android, and everything works fine.

If what you say is true, then this is not a DUFS issue, but rather a problem with your browser.

Sorry, dufs can't do anything about it.

**Comment by SoulLinkIly** [comment]
能分享一下你的浏览器吗？谢谢

**Comment by sigoden** [comment]
Chrome

**Comment by SoulLinkIly** [comment]
你是对的，edge也可以，华为自带的浏览器和via都不行，我之前只用了这两个尝试。
谢谢你。
