### ISSUE TITLE
Customizing favicon, page title, font/font color

### ISSUE THREAD

**Issue by spoisseroux** [sigoden/dufs#469]
I see [here](https://github.com/sigoden/dufs?tab=readme-ov-file#customize-ui) that Dufs UI is able to be customized, but I'm not really sure how to go about doing it without creating a whole new UI. I just want to change things like the page title, favicon, and font/font-color. Is it possible to do this simply?

**Comment by sigoden** [comment]
If you only need to make slight adjustments to the current user interface, you can modify it based on the dufs's [assets](https://github.com/sigoden/dufs/tree/main/assets).

```sh
git clone https://github.com/sigoden/dufs
cd dufs
cp assets/ new-assets/
# Modify new-assets to match your needs.
dufs --assets new-asets
```

**Comment by sigoden** [comment]
The UI doesn't use any frameworks, just plain html/js/css. As long as you have some basic knowledge of web development, it shouldn't be difficult to modify.

```
assets/
├── favicon.ico
├── index.css
├── index.html
└── index.js
```

**Comment by spoisseroux** [comment]
Thank you! Exactly what I needed to know, sorry about the trouble
