### ISSUE TITLE
curl http://127.0.0.1:5000?json not working

### ISSUE THREAD

**Issue by RamonDonadeu** [sigoden/dufs#471]
**Problem**

(sorry for my last post)
I'm trying to use "curl http://127.0.0.1:5000?json" to get the structure of my dufs container, but it says:
`zsh: no matches found: http://127.0.0.1:5000?json`
same happens with `q="filename"`
and `?simple`
I was expecting a json structure with all the files and folfers of my service.

**Configuration**

docker run -v `pwd`:/data -p 5000:5000 --rm sigoden/dufs /data -A

**Log**

Dufs is not even logging anything

**Screenshots/Media**

![Captura de pantalla 2024-10-25 a las 11 33 00](https://github.com/user-attachments/assets/cb116db6-4930-4cfc-b0e7-98040df3e826)

**Environment Information**
 - Dufs version: latest I suppose
 - Browser/Webdav info: MacOs Terminal
 - OS info: Docker container, on MacOs
 - Proxy server (if any):  none

**Comment by sigoden** [comment]
@RamonDonadeu 

> Dufs is not even logging anything

This means that dufs won't accept any request.

I'm not familiar with zsh, but based on the error message, I suspect it’s an issue with zsh, as it doesn’t seem to be calling dufs at all.

You may wrap the URL in quotes.
```
dufs 'http://127.0.0.1:5000?json'
```
Or try running it in another shell, such as bash.
```
# in bash
dufs http://127.0.0.1:5000?json
```

**Comment by RamonDonadeu** [comment]
Yes, it worked in bash!

But as I said in #470, I'm trying to do this call from a .net Backend, and I'm not getting the content of the response... Now I know that it works, I'll keep investigating thanks!

**Comment by RamonDonadeu** [comment]
Nevermind... I found the problem... Thanks anyway!
