### ISSUE TITLE
Provide markdown rendering support

### ISSUE THREAD

**Issue by hugo-akaora** [sigoden/dufs#475]
## Specific Demand

Would be great to provide markdown rendering support in dufs, like in https://github.com/brson/basic-http-server

## Implement Suggestion

[md-block: Render styleable Markdown in your HTML](https://md-block.verou.me/) is great.

I found an easy way to do it:

In assets folder, in `index.html` add between `<head></head>`: `<script type="module" src="__ASSETS_PREFIX__markdown/md-block.js"></script>`

Extract [markdown folder](https://github.com/user-attachments/files/17571084/markdown.zip) (it's basically offline md-block/marked.js/dompurify) folder in assets folder. You could also fetch JS using a CDN but I do not like it (and my dufs instance must work offline too).

Then add `<md-block untrusted src="README.md"></md-block>` to render `README.md`when one exists in folder.

Don't know if you would be interested in implementing it, it's extra JS and it's probably a niche. 

I'm personally satisfied by my workaround :) So I posted an issue so it could be useful for others.

Feed free to close it, and many thanks for dufs! <3

**Comment by sigoden** [comment]
Dufs will never treat any file differently.

Users who need markdown rendering should use a custom UI.

**Comment by image72** [comment]
@sigoden current, markdown file is very important file format in llm, document and many more place required. when render markdown file just need place `  <script src="https://cdn.jsdelivr.net/npm/marked/lib/marked.umd.js"></script>` will auto process pass markdown content as html page.
I think that very usefully.

reference project:
https://github.com/MichielDeMey/marked-mermaid
https://github.com/markedjs/marked

**Comment by xcatliu** [comment]
I ended up with a simple client-side workaround that requires zero changes to dufs itself:

  1. Put a single `md.html` at the dufs root
  2. Access any markdown file via: https://your-dufs-server/md.html?path=path/to/file.md

  The HTML fetches the raw markdown from the same origin (no CORS issues) and renders it in the browser using [marked.js](https://github.com/markedjs/marked) + [github-markdown-css](https://github.com/sindresorhus/github-markdown-css):

```html
  <!DOCTYPE html>
  <html>
  <head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Loading...</title>
  <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/github-markdown-css/github-markdown-light.min.css">
  <style>
    body { max-width: 980px; margin: 0 auto; padding: 2rem 1rem; }
  </style>
  </head>
  <body>
  <article class="markdown-body" id="content"><p>Loading...</p></article>
  <script>
  (async () => {
    const el = document.getElementById('content');
    const path = new URLSearchParams(location.search).get('path');
    if (!path) { el.innerHTML = '<p>Usage: ?path=your/file.md</p>'; return; }
    document.title = path.split('/').pop();
    try {
      const res = await fetch('/' + path.replace(/^\//, ''));
      if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
      el.innerHTML = marked.parse(await res.text());
    } catch (e) {
      el.innerHTML = `<p>Failed to load /${path}: ${e.message}</p>`;
    }
  })();
  </script>
  </body>
  </html>
```

Not a native solution, but it works well enough — no server-side changes, no build step, just one static HTML file.
