### ISSUE TITLE
Support for external authentication file

### ISSUE THREAD

**Issue by R-Bose** [sigoden/dufs#485]
## Specific Demand

Example:
Users: usr1 usr2
Paths: /disk0/usr1 /disk1/usr2 (both users have "shared" folder)
Permissions: Each user can read other user's shared folder and can write to their own path. 
Problem: Current implementation forces me to duplicate authentication info for each dufs instance

## Implement Suggestion

add support for external auth file which would contain user and encrypted pass, then just the username can be referred for setting permissions.

**Comment by sigoden** [comment]
We will not suport this feature.

Dufs already support config file (`config.yaml`), a seperated auth file doesn't have much significance.
