### ISSUE TITLE
**dufs**  `rw` permission is not in effect

### ISSUE THREAD

**Issue by 123GitHub0123** [sigoden/dufs#486]
**dufs** in the specified user account password login, feel the permission management is not enough, set 'rw' permission, only download and write permission, write permission is not effective, or less save button, because I can consult the content of this text box, and write it, but can not save it, perhaps this is the reason why the write permission is not effective.

> This is where I set the -auth parameter, permission is' rw 'in case the directory operates on the file icon. It is incomplete.
![image](https://github.com/user-attachments/assets/1916eaf3-9d10-4f44-842f-9580a399a702)
![image](https://github.com/user-attachments/assets/27320950-cf9d-41dc-8252-2156307cd20e)

> I can read it, write it, but I can't save it.
![image](https://github.com/user-attachments/assets/e2ee8884-877f-48b4-87de-822b709fdd3b)
![image](https://github.com/user-attachments/assets/66cd0521-850c-4ca4-a4a7-3c01810e4711)
![image](https://github.com/user-attachments/assets/3c7a8d84-b23f-4dbf-b1f7-3402124fe3eb)

**Comment by sigoden** [comment]
The `--allow-*` options globally control which operations dufs supports.
The `-a <auth-role>` controls the permissions granted to a user on specific paths.
you need to add `--allow-*` flags.
