### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by 6eh01der** [sigoden/dufs#487]
dufs is just a great thing and It could be greater if it will support LDAP authentication - OpenLDAP, Active Directory, etc.

I'm not the RUST programmer but if it could help there are three LDAP implementations in RUST:

1. https://github.com/inejge/ldap3 - there is no built-in support for connection pooling, automatic fallback or reconnections
2. https://github.com/dequbed/rust-ldap - last activity was 7 years ago
3. https://github.com/keaz/simple-ldap (wraps №1)

So maybe there is nothing better than C LDAP library...
https://users.rust-lang.org/t/ldap-library-for-rust/10449

**Comment by sigoden** [comment]
Sorry, we will not support this feature.

We don't think a simple file service needs such a complicated authentication mechanism.
