### ISSUE TITLE
Question: How to gracefully shutdown dufs from CLI

### ISSUE THREAD

**Issue by haexhub** [sigoden/dufs#488]
Hi,

I've got a question regarding shutting down the server over cli. Couldn't find anything in the documenation. In the changelog I found it was mentioned, that this possibility is available but couldn't find anything further.
Is there anything like dufs --shutdown?

**Comment by sigoden** [comment]
Dufs don't handle gracefully shutdown. A simple file service does not require this feature.

In the future, if graceful shutdown is supported, it will also be seamless.

Always use ctrl+c or kill to stop dufs.
