### ISSUE TITLE
HealthCheck Suggestion

### ISSUE THREAD

**Issue by capncybo** [sigoden/dufs#490]
Thanks Sigoden, I Absolutely LOVE your DUFS software.
Very much appreciated!!!

Perhaps your intent was ONLY for local server verification 
[Note: I previously missed the (example) being ONLY the local loopback address 127.0.0.1]
Ex)
curl http://10.19.38.66:50000/__dufs__/health
{"status":"OK"}

And Re-reading it now... (It makes complete sense to me).
However, while previously tinkering around (with some other simple bash scripts) I was thinking perhaps something like...
Ex)
curl http://10.19.38.66:50000/__dufs__/health?simple
OK

Might be nice, & probably easy for you to implement.
Although I do understand... Almost any response should indicate the server is up & online...
So, I'm no longer sure of the validity of my ask, LOL

**Comment by sigoden** [comment]
dufs already supports the health api #474

**Comment by capncybo** [comment]
Thanks BUT, what I meant was... for DUFS to answer the HealthCheck in a **simple** format.
 NOT just the already existing reply in json format.
But only If you append: "?simple" to the URL
Ex)
curl http://10.19.38.66:50000/__dufs__/health**?simple**
OK

**Comment by sigoden** [comment]
We will not support this feature.
