### ISSUE TITLE
Hashed-Passwords not working with docker compose

### ISSUE THREAD

**Issue by Rogibaer** [sigoden/dufs#491]
**Problem**

Using hashed passwords in docker compose doesnt work.

**Configuration**
I use docker compose to deploy DUFS.
This is my compose file:
version: '3.8'

services:
  dufs:
    image: sigoden/dufs
    container_name: dufs
    ports:
      - "5000:5000"
    volumes:
      - cert:/cert
      - /BINDPATH:/data  # Path obfuscated
    command: 	/data --tls-cert /cert/MyCertificate.crt --tls-key /cert/MyKey.key --allow-all 
		-a 'admin:$6$AWXrSMrBJQ0ZquNX$yHlpug.8wh.r1ebcWBFBAstBpaNi/iQCPHTOB3sAaie515bI8kW1./AyQ1yiX0z0IWb7UtGmRbDti0okA0ida.@/:rw'
    restart: unless-stopped
volumes:
      cert:

The login doesnt work.
If I try to save my password-database using Keepass to the webDAV-Location the Console of the Container just prints:
2024-11-26T12:18:05Z INFO - 10.5.101.4 "GET /FILENAME" 401
Which obviously means "forbidden"

If i use the password in plain text its working like a charm.

If you need more logs for troubleshooting  please let me know!

**Environment Information**
 - Dufs version: Latest
 - Browser/Webdav info: Firefox or Chrome -> Both not Working
 - OS info: Windows 11

**Comment by sigoden** [comment]
Dufs has complete testing, so it cannot be an issue with Dufs itself. 

You need to investigate this problem on your own; I am unable to help.

**Comment by Rogibaer** [comment]
Found the issue.
For anyone wondering:
In your compose.yml if you are using envoiroment-variables you need to escape the $ symbol by doubleing it to $$.
You can compare your compose.yml to the actual data interpreted by docker compose using docker-compose config.
