### ISSUE TITLE
Authorization does not work

### ISSUE THREAD

**Issue by estepnv** [sigoden/dufs#495]
**Problem**

the authorization does not work for browser app, the server does not force me to submit http basic creds.
also I use ubuntu nautilus webdav capabilities, and it looks like it simply ignores the auth config too, allowing me to browse files without specifying creds. but it forces me to specify creds for obsidian remotelysave plugin webdav option. 
also the app ignores render-index or render-spa configs. no matter what's specified, it serves the web app.

am I doing something wrong?
any clues on how to setup this properly?

thanks

**Configuration**
via env variables
```
          "TZ": "Europe/Moscow"
          "DUFS_AUTH": "{{dufs_eugene_username}}:{{dufs_eugene_password}}@/eugene:rw"
          "DUFS_AUTH_METHOD": "digest"
          "DUFS_RENDER_SPA": "false"
          "DUFS_RENDER_INDEX": "false"
          "DUFS_RENDER_TRY_INDEX": "false"
          "DUFS_ENABLE_CORS": "false"
          "DUFS_ALLOW_ALL": "false"
          "DUFS_ALLOW_UPLOAD": "true"
          "DUFS_ALLOW_DELETE": "true"
          "DUFS_ALLOW_SEARCH": "true"
          "DUFS_ALLOW_SYMLINK": "true"
          "DUFS_ALLOW_ARCHIVE": "true"
```

**Screenshots/Media**

**Environment Information**
 - Dufs version: 0.41.0
 - Browser/Webdav info: brave latest
 - OS info: ubuntu 24.04
 - Proxy server (if any): traefik 3

**Comment by sigoden** [comment]
> the authorization does not work for browser app, the server does not force me to submit http basic creds.

If the request does not include authorization, dufs will return a 401 status code,  the browser will prompt the user to enter a username and password. This process is ensured by the browser and is unrelated to dufs.


> also I use ubuntu nautilus webdav capabilities, and it looks like it simply ignores the auth config too, allowing me to browse files without specifying creds. 

Some WebDAV clients do not send credentials by default. This is why some users reported #476.


Dufs is a mature project, and all functions have been tested. There shouldn't be any obvious authorization issues. If there are issues, it's mostly a problem on your end; you need to resolve it yourself.

**Comment by estepnv** [comment]
thank for reply
