### ISSUE TITLE
Support `!` operator when authorizing path

### ISSUE THREAD

**Issue by peterroe** [sigoden/dufs#499]
## Specific Demand

* admin: can read and write all file
* user1: can read all file
* default: can't read /privete

```bash
docker run -v `pwd`:/data --detach sigoden/dufs /data -A  -a admin:admin@/:rw -a user1:user1@/:ro -a 
@/ro,!/private
```

**Comment by sigoden** [comment]
We do not support features, as this would make permissions extremely complex.

Please design the paths and permissions carefully. 
> Tip: You can use symlinks to simplify the design.

**Comment by peterroe** [comment]
You are right, maybe a better way is to create a new `/public` directory specifically for making the directory readable by anyone.
