### ISSUE TITLE
Feature Request: Upload file via url

### ISSUE THREAD

**Issue by breezechen** [sigoden/dufs#503]
## Specific Demand

In situations where a user’s local network environment is restricted by a firewall, but the file server can freely access external resources, a remote download feature can be extremely helpful. With this capability, the user can direct the file server to download the desired file first, and then retrieve it from the server to their local machine. This circumvents network limitations and simplifies the file acquisition process.

**Comment by sigoden** [comment]
We will not support this feature. This functionality is beyond the scope of file server.

Maybe you can implement a remote file download service by yourself, and then share the file system with dufs.
