### ISSUE TITLE
can auth the specified file?it seems that only can auth dir now,rigth?

### ISSUE THREAD

**Issue by yuf19-2022** [sigoden/dufs#505]
-a, --auth <rules>         Add auth roles, e.g. user:pass@/dir1:rw,/dir2
can auth the specified file?it seems that only can auth dir now,rigth?

**Comment by sigoden** [comment]
dufs can auth on specific file.

**Comment by sigoden** [comment]
I have tested it, and everything works fine.

```
mkdir project
echo hello world > project/index.html
dufs . -a admin:admin@/project/index.html
```

Access `http://127.0.0.1:5000/project/index.html`. The browser prompts for authentication; after entering the username and password, I can access the page.

**Comment by sigoden** [comment]
> he can ascess ip:5000/a and ip:5000/a/b.

First, it's important to understand that there are three types of permissions in dufs: index, read, and write. 

The `-a user:pass@/a/b/` grants read permissions for the directory `a/b` and grants index permissions for the directory `/a`.
