### ISSUE TITLE
Add a configuration item to set unix domain socket files permissions for docker

### ISSUE THREAD

**Issue by wayilive** [sigoden/dufs#506]
Add a configuration item to set unix domain socket files permissions, this feature exists in alist, alist's configure file has a configuration item 'unix_file_perm' and usually has a value '0666'.

I want to combine using dufs and nginx in one docker compose file and share the unix domain socket between container and the host.

**Comment by sigoden** [comment]
We will not support this feature. This configuration is too trivial. 

Please change the file permissions manually after Dufs creates the socket file. 

Another option is to change the umask settings. The default file permissions for a Unix domain socket path created by a Rust program are determined by the umask setting.

**Comment by Puqns67** [comment]
PS: In systemd.service, you can add this line to change UNIX socket permissions after dufs start.
* This assumes that your UNIX socket is under `/run/dufs`, and you can modify it yourself.
```service
ExecStartPost=/usr/bin/bash -c '/usr/bin/sleep 1; for file in /run/dufs/*; do if [ -S "$file" ]; then /usr/bin/chmod 0660 "$file"; fi; done'
```
