### ISSUE TITLE
Why doesn't the download folder button show?

### ISSUE THREAD

**Issue by ma3252788** [sigoden/dufs#507]
**Problem**

I installed dufs 0.43.0 under ARM linux, but I don't see the option to download the folder, and my interface is different from the official demo interface

<img width="859" alt="image" src="https://github.com/user-attachments/assets/58d5739b-e026-4da3-9d15-da3a2fd00fd8" />

**Environment Information**
 - Dufs version: 0.43.0
 - Browser/Webdav info:
 - OS info: ubuntu Linux arm 5.15.0-1055-oracle #61~20.04.1-Ubuntu SMP Tue Mar 26 09:23:06 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
 - Proxy server (if any):

**Comment by sigoden** [comment]
To be honest, I really hate these kinds of questions. Can’t you just read the README in detail?

use `--allow-archive` or `--allow-all`
