### ISSUE TITLE
Unable to exit

### ISSUE THREAD

**Issue by ma3252788** [sigoden/dufs#508]
**Problem**

I tried using ctrl + c for exit, but to no avail

<img width="715" alt="image" src="https://github.com/user-attachments/assets/04ebecc2-7900-4909-a867-2b29b6525fd6" />

**Configuration**

**Environment Information**
 - Dufs version: 0.43.0
 - Browser/Webdav info:
 - OS info:Linux arm 5.15.0-1055-oracle #61~20.04.1-Ubuntu SMP Tue Mar 26 09:23:06 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
 - Proxy server (if any):

**Comment by sigoden** [comment]
This project has been going on for so long, and you are the only one reporting this issue. 

It might be a problem with your system. For example, when using SSH, the network happens to be unstable.

Or it might be an issue unique to arch64 Linux; I can't confirm either way.

Sorry, for any reason, this issue cannot be handled at the moment.
