### ISSUE TITLE
auth cannot remain in all path

### ISSUE THREAD

**Issue by yuf19-2022** [sigoden/dufs#509]
eg:/a/b/c is a non-auth path,i enter this path,and i login and auth ok,when i back to its parent path:/a/b,even if i refresh my brower,i cannot see other dir thst needs to be authed.i have to auth in /a/b again.

**Comment by sigoden** [comment]
Cannot confirm the problem.

Please create a new issue and follow the issue guide to provide the configuration, screenshots, and logs.
