### ISSUE TITLE
Suggestion for the documentation

### ISSUE THREAD

**Issue by dhenry123** [sigoden/dufs#513]
Hi
I was looking for a lighter solution than Nextcloud to host my files, and your solution is really cool.
Installed in a kubernetes cluster, I just had a slight problem with logs, the service is exposed behind a load balancer, and $remote_addr shows the load balancer ip address (expected).
Using your documentation https://github.com/sigoden/dufs?tab=readme-ov-file#log-format, I finally found the right variable: "**$http_x_forwarded_for**". it may help others...

Thank you so much.

**Comment by sigoden** [comment]
Thank you for sharing.
