### ISSUE TITLE
Only show some directories and hidden all the others?

### ISSUE THREAD

**Issue by jiangjiangflies** [sigoden/dufs#516]
I have so many files and directories in the serve path but I only need to display 2 or three directories. If use hidden option, it will be a long list of argument,e.g. --hidden 'A' --hidden 'B' ... to hide directory A,B....
Is there an easy way to only show directory D and directory E while hiding all other directories and files?

**Comment by sigoden** [comment]
It is recommended to use symlinks to group related directories together.
