### ISSUE TITLE
i have a problem about "--allow-symlink "

### ISSUE THREAD

**Issue by yuf19-2022** [sigoden/dufs#518]
--allow-symlink        Allow symlink to files/folders outside root directory
i cannot understand how it works

**Comment by sigoden** [comment]
The `--allow-symlink` option in `dufs` is used to permit symbolic links (symlinks) that point to files or folders outside the specified root directory of the file server. Normally, for security reasons, file servers restrict access to only the files and folders within a defined root directory to prevent exposure of sensitive information from other parts of the system. 

When you enable `--allow-symlink`, `dufs` allows these symlinks to be followed, which means users can access files or folders outside the root directory if symlinks within the root directory point to them.

Use this option carefully, as it can inadvertently expose unintended files or directories outside your control to users.

If you still don't understand, please create a symlink directory to test it yourself.

**Comment by sigoden** [comment]
I guess you're using a Windows system. Please use `mklink` to create the symlink.
