### ISSUE TITLE
docker 容器运行时，如何增加下载和删除等功能

### ISSUE THREAD

**Issue by axin7** [sigoden/dufs#72]
使用docker时，默认只有下载功能，docker exec进不去容器， 该怎么增加下载和删除等功能

**Comment by sigoden** [comment]
docker镜像基于scratch，大小只有3.4M，不含操作系统，所以没法运行docker exec 进入。

运行容器时，可以在尾部带上选项，示例如下
```
docker run -v `pwd`:/data -p 5000:5000 --rm -it sigoden/dufs /data -A
```

**Comment by axin7** [comment]
好的，谢了
