### ISSUE TITLE
cannot bind address 0.0.0.0

### ISSUE THREAD

**Issue by changcui** [sigoden/dufs#74]
I cannot bind address 0.0.0.0, as a result, i cannot use the public IP to access the file server.
I found out the source code of args.rs just filter out the address, why?

**Comment by sigoden** [comment]
the default is bind to 0.0.0.0 

cloud you post the log?

**Comment by changcui** [comment]
Listening on:
  https://127.0.0.1:38964/
  https://172.17.0.1:38964/
  https://172.18.0.1:38964/
  https://172.19.0.3:38964/
  https://[::1]:38964/
It listens on all inet address, not https://0.0.0.0:38964/

**Comment by sigoden** [comment]
`0.0.0.0` is used on servers to designate a service may bind to all network interfaces.

it doesn't exist physically. so dufs list all bind addresses except 0.0.0.0

you still use the public IP.

**Comment by changcui** [comment]
Thanks very much, it's okay!
