### ISSUE TITLE
create/delete folder

### ISSUE THREAD

**Issue by leolulu** [sigoden/dufs#90]
Hi sigoden, thanks for your development, this tool helps me a lot. Just love it.

Sometimes, when I upload new files and want to classify them from previous ones, I will create a folder and put them is there.
Since dufs does not support creating new folder on web UI, I have to go to the terminal and run mkdir command.
So if create/delete folder is supported on web UI, it will be very helpful.

Hope to hear your opinion.
Thanks in advance.

**Comment by sigoden** [comment]
Dufs already support create/delete folders. 

First you have to allow upload/delete operations with `--allow-upload`/`--allow-delete` or `--allow-all`/`-A`.

You can see delete icons in actions column, click  them to delete folders/files.

Creating folders is not so obvious but dufs also supports. If you want create a folder named `dir1`,  just goto `http://localhost:5000/dir1` and upload some files.

**Comment by sigoden** [comment]
drag & drop a folder also works.

**Comment by leolulu** [comment]
got it, thanks.

**Comment by leolulu** [comment]
@sigoden 
Tested, here are some feedbacks:
1. drag & drop an empty folder, nothing happend.
2. put a new name in the url, gives error
![image](https://user-images.githubusercontent.com/35873316/177246427-1885c161-3451-4faf-95f6-e22a602728fe.png)

Anyway, drag&drop nonempty folder works.

**Comment by sigoden** [comment]
1. drag & drop can only upload files, have no effect on empty folder is expected behavior

2. url need / at end to indicate a folder other than file

**Comment by leolulu** [comment]
> 2. url need `/` at end to indicate a folder other than a file, check `<origin>/dir2/`

cool, it works.
