### ISSUE TITLE
retry when upload fail

### ISSUE THREAD

**Issue by leolulu** [sigoden/dufs#94]
while uploading a whole folder, some files may fail.
![image](https://user-images.githubusercontent.com/35873316/177245888-64eb6fd0-adfa-482d-bb44-7734aff0cc2e.png)
Maybe a retry button could be helpful, or auto retry could be better.

**Comment by sigoden** [comment]
why so many failures, could you post logs？

I will not support retrying because I think failure is rare case. And reuploading need allow-delete permission.

**Comment by leolulu** [comment]
weird. I did the identical uploading again, and got two failures.
```
……
……
Duplicate.Cleaner.Pro.5.16.0.0/Magick.NET-Q8-AnyCPU.dll ✗
……
……
Duplicate.Cleaner.Pro.5.16.0.0/x64/SQLite.Interop.dll ✗
……
……
```

Then the log during this uploading:
```
……
……
[2022-07-05T05:21:13.130Z INFO] 192.168.123.221 "PUT /Duplicate.Cleaner.Pro.5.16.0.0/Magick.NET-Q8-AnyCPU.dll" - 201
……
……
[2022-07-05T05:22:39.590Z INFO] 192.168.123.221 "PUT /Duplicate.Cleaner.Pro.5.16.0.0/x86/SQLite.Interop.dll" - 201
……
……
```
Finally after I refresh the web page, these files do exists, so is in the local file system. 
Seems the error only appears on the web page.

**Comment by sigoden** [comment]
ui should not show failure if log shows success.

Could you open webdev tools and take a screenshot of the network/console panel?

**Comment by leolulu** [comment]
sure, I take one of the failures as example.

web page result:   
Duplicate.Cleaner.Pro.5.16.0.0/Magick.NET.Core.dll   ✗

backend log:
[2022-07-05T10:27:48.897Z INFO] 192.168.123.221 "PUT /Duplicate.Cleaner.Pro.5.16.0.0/Magick.NET.Core.dll" - 201 

webdev network:
![image](https://user-images.githubusercontent.com/35873316/177309707-19e78e10-6e6b-4df9-a7ea-5a7bc47a3596.png)

webdev console:
![image](https://user-images.githubusercontent.com/35873316/177310079-c68796ce-c5c0-4493-a69b-da752357d099.png)

**Comment by sigoden** [comment]
dufs never returns 502.  Are your run dufs behind a proxy?

**Comment by leolulu** [comment]
Yes, I deploy dufs on my local machine, and expose the service through frp(a reverse proxy).
Then access by the public ip and port.
Could this be the reason?

**Comment by leolulu** [comment]
sure, I will try.
And Since it's not the problem of program itself, I think this thread could be closed.
Thanks for you tech support  :)

**Comment by sigoden** [comment]
Issue #95 is open to handle concurrency.
