### ISSUE TITLE
CORS needs 'Access-Control-Allow-Methods' header

### ISSUE THREAD

**Issue by XSnelliusX** [sigoden/dufs#99]
**Problem**
Im trying to upload files to a Dufs server from an other server over http.
For this I run the Dufs server with this command, to anable CORS: `dufs -A --enable-cors`
But the PUT Request I send to the Server is blocked with the following error message:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at _xxx_. (Reason: Did not find method in CORS header ‘Access-Control-Allow-Methods’).

After looking in to the server.rs I found that in the [add_cors](https://github.com/sigoden/dufs/blob/cb1f3cddeaf0f4306430189a2ecd2a04151fae06/src/server.rs#L1006-L1017) function only the `AccessControlAllowOrigin`, `AccessControlAllowCredentials` and `AccessControlAllowHeaders`  headers are set. However WebDav needs the PUT method and therefor the `AccessControlAllowMethods` header is needed.

**Environment:**
 - Dufs version: 0.25.0
 - Browser/Webdav Info: Firefox Version 102.0.1
 - OS Info: Windows 11

**Comment by jens1o** [comment]
Thank you very much for confirming and implementing the fix, @sigoden ! :) It is stunning that you are reacting this fast to newly made issues! :)
